/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ConfigPbsCreatePbsRequest,
    ConfigPbsCreatePbsRequestFromJSON,
    ConfigPbsCreatePbsRequestToJSON,
} from '../models/ConfigPbsCreatePbsRequest';
import {
    type ConfigPbsCreatePbsResponse,
    ConfigPbsCreatePbsResponseFromJSON,
    ConfigPbsCreatePbsResponseToJSON,
} from '../models/ConfigPbsCreatePbsResponse';
import {
    type ConfigPbsDeletePbsResponse,
    ConfigPbsDeletePbsResponseFromJSON,
    ConfigPbsDeletePbsResponseToJSON,
} from '../models/ConfigPbsDeletePbsResponse';
import {
    type ConfigPbsGetPbsResponse,
    ConfigPbsGetPbsResponseFromJSON,
    ConfigPbsGetPbsResponseToJSON,
} from '../models/ConfigPbsGetPbsResponse';
import {
    type ConfigPbsReadConfigResponse,
    ConfigPbsReadConfigResponseFromJSON,
    ConfigPbsReadConfigResponseToJSON,
} from '../models/ConfigPbsReadConfigResponse';
import {
    type ConfigPbsUpdateConfigRequest,
    ConfigPbsUpdateConfigRequestFromJSON,
    ConfigPbsUpdateConfigRequestToJSON,
} from '../models/ConfigPbsUpdateConfigRequest';
import {
    type ConfigPbsUpdateConfigResponse,
    ConfigPbsUpdateConfigResponseFromJSON,
    ConfigPbsUpdateConfigResponseToJSON,
} from '../models/ConfigPbsUpdateConfigResponse';
import {
    type PmgError,
    PmgErrorFromJSON,
    PmgErrorToJSON,
} from '../models/PmgError';

export interface ConfigPbsApiCreatePbsRequest {
    configPbsCreatePbsRequest: ConfigPbsCreatePbsRequest;
}

export interface ConfigPbsApiDeletePbsRequest {
    remote: string;
}

export interface ConfigPbsApiReadConfigRequest {
    remote: string;
}

export interface ConfigPbsApiUpdateConfigRequest {
    remote: string;
    configPbsUpdateConfigRequest?: ConfigPbsUpdateConfigRequest;
}

/**
 * 
 */
export class ConfigPbsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPbs without sending the request
     */
    async createPbsRequestOpts(requestParameters: ConfigPbsApiCreatePbsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['configPbsCreatePbsRequest'] == null) {
            throw new runtime.RequiredError(
                'configPbsCreatePbsRequest',
                'Required parameter "configPbsCreatePbsRequest" was null or undefined when calling createPbs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/pbs`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigPbsCreatePbsRequestToJSON(requestParameters['configPbsCreatePbsRequest']),
        };
    }

    /**
     * Add Proxmox Backup Server remote instance.
     * Add Proxmox Backup Server remote instance
     */
    async createPbsRaw(requestParameters: ConfigPbsApiCreatePbsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPbsCreatePbsResponse>> {
        const requestOptions = await this.createPbsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPbsCreatePbsResponseFromJSON(jsonValue));
    }

    /**
     * Add Proxmox Backup Server remote instance.
     * Add Proxmox Backup Server remote instance
     */
    async createPbs(requestParameters: ConfigPbsApiCreatePbsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPbsCreatePbsResponse> {
        const response = await this.createPbsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePbs without sending the request
     */
    async deletePbsRequestOpts(requestParameters: ConfigPbsApiDeletePbsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling deletePbs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/pbs/{remote}`;
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an PBS remote
     * Delete an PBS remote
     */
    async deletePbsRaw(requestParameters: ConfigPbsApiDeletePbsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPbsDeletePbsResponse>> {
        const requestOptions = await this.deletePbsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPbsDeletePbsResponseFromJSON(jsonValue));
    }

    /**
     * Delete an PBS remote
     * Delete an PBS remote
     */
    async deletePbs(requestParameters: ConfigPbsApiDeletePbsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPbsDeletePbsResponse> {
        const response = await this.deletePbsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPbs without sending the request
     */
    async getPbsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/pbs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all configured Proxmox Backup Server instances.
     * List all configured Proxmox Backup Server instances
     */
    async getPbsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPbsGetPbsResponse>> {
        const requestOptions = await this.getPbsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPbsGetPbsResponseFromJSON(jsonValue));
    }

    /**
     * List all configured Proxmox Backup Server instances.
     * List all configured Proxmox Backup Server instances
     */
    async getPbs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPbsGetPbsResponse> {
        const response = await this.getPbsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readConfig without sending the request
     */
    async readConfigRequestOpts(requestParameters: ConfigPbsApiReadConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling readConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/pbs/{remote}`;
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Proxmox Backup Server remote configuration.
     * Get Proxmox Backup Server remote configuration
     */
    async readConfigRaw(requestParameters: ConfigPbsApiReadConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPbsReadConfigResponse>> {
        const requestOptions = await this.readConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPbsReadConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get Proxmox Backup Server remote configuration.
     * Get Proxmox Backup Server remote configuration
     */
    async readConfig(requestParameters: ConfigPbsApiReadConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPbsReadConfigResponse> {
        const response = await this.readConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateConfig without sending the request
     */
    async updateConfigRequestOpts(requestParameters: ConfigPbsApiUpdateConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling updateConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        // Optional body: only emit Content-Type when the body is actually provided.
        // PVE/PMG Perl HTTP server rejects empty bodies with Content-Type: application/json
        // ("malformed JSON string"), and other Proxmox products are equally fussy.
        if (requestParameters['configPbsUpdateConfigRequest'] != null) {
            headerParameters['Content-Type'] = 'application/json';
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/config/pbs/{remote}`;
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigPbsUpdateConfigRequestToJSON(requestParameters['configPbsUpdateConfigRequest']),
        };
    }

    /**
     * Update PBS remote settings.
     * Update PBS remote settings
     */
    async updateConfigRaw(requestParameters: ConfigPbsApiUpdateConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigPbsUpdateConfigResponse>> {
        const requestOptions = await this.updateConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigPbsUpdateConfigResponseFromJSON(jsonValue));
    }

    /**
     * Update PBS remote settings.
     * Update PBS remote settings
     */
    async updateConfig(requestParameters: ConfigPbsApiUpdateConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigPbsUpdateConfigResponse> {
        const response = await this.updateConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
