/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NodesBackupBackupRequest,
    NodesBackupBackupRequestFromJSON,
    NodesBackupBackupRequestToJSON,
} from '../models/NodesBackupBackupRequest';
import {
    type NodesBackupRestoreRequest,
    NodesBackupRestoreRequestFromJSON,
    NodesBackupRestoreRequestToJSON,
} from '../models/NodesBackupRestoreRequest';
import {
    type NodesPbsCreateTimerRequest,
    NodesPbsCreateTimerRequestFromJSON,
    NodesPbsCreateTimerRequestToJSON,
} from '../models/NodesPbsCreateTimerRequest';
import {
    type NodesPbsCreateTimerResponse,
    NodesPbsCreateTimerResponseFromJSON,
    NodesPbsCreateTimerResponseToJSON,
} from '../models/NodesPbsCreateTimerResponse';
import {
    type NodesPbsDeleteTimerResponse,
    NodesPbsDeleteTimerResponseFromJSON,
    NodesPbsDeleteTimerResponseToJSON,
} from '../models/NodesPbsDeleteTimerResponse';
import {
    type NodesPbsForgetSnapshotResponse,
    NodesPbsForgetSnapshotResponseFromJSON,
    NodesPbsForgetSnapshotResponseToJSON,
} from '../models/NodesPbsForgetSnapshotResponse';
import {
    type NodesPbsGetGroupSnapshotsResponse,
    NodesPbsGetGroupSnapshotsResponseFromJSON,
    NodesPbsGetGroupSnapshotsResponseToJSON,
} from '../models/NodesPbsGetGroupSnapshotsResponse';
import {
    type NodesPbsGetPbsResponse,
    NodesPbsGetPbsResponseFromJSON,
    NodesPbsGetPbsResponseToJSON,
} from '../models/NodesPbsGetPbsResponse';
import {
    type NodesPbsGetSnapshotsResponse,
    NodesPbsGetSnapshotsResponseFromJSON,
    NodesPbsGetSnapshotsResponseToJSON,
} from '../models/NodesPbsGetSnapshotsResponse';
import {
    type NodesPbsListTimerResponse,
    NodesPbsListTimerResponseFromJSON,
    NodesPbsListTimerResponseToJSON,
} from '../models/NodesPbsListTimerResponse';
import {
    type NodesPbsRemoteIndexResponse,
    NodesPbsRemoteIndexResponseFromJSON,
    NodesPbsRemoteIndexResponseToJSON,
} from '../models/NodesPbsRemoteIndexResponse';
import {
    type NodesPbsRestoreResponse,
    NodesPbsRestoreResponseFromJSON,
    NodesPbsRestoreResponseToJSON,
} from '../models/NodesPbsRestoreResponse';
import {
    type NodesPbsRunBackupResponse,
    NodesPbsRunBackupResponseFromJSON,
    NodesPbsRunBackupResponseToJSON,
} from '../models/NodesPbsRunBackupResponse';
import {
    type PmgError,
    PmgErrorFromJSON,
    PmgErrorToJSON,
} from '../models/PmgError';

export interface NodesPbsApiCreateTimerRequest {
    node: string;
    remote: string;
    nodesPbsCreateTimerRequest?: NodesPbsCreateTimerRequest;
}

export interface NodesPbsApiDeleteTimerRequest {
    node: string;
    remote: string;
}

export interface NodesPbsApiForgetSnapshotRequest {
    backupId: string;
    backupTime: string;
    node: string;
    remote: string;
}

export interface NodesPbsApiGetGroupSnapshotsRequest {
    backupId: string;
    node: string;
    remote: string;
}

export interface NodesPbsApiGetPbsRequest {
    node: string;
}

export interface NodesPbsApiGetSnapshotsRequest {
    node: string;
    remote: string;
}

export interface NodesPbsApiListTimerRequest {
    node: string;
    remote: string;
}

export interface NodesPbsApiRemoteIndexRequest {
    node: string;
    remote: string;
}

export interface NodesPbsApiRestoreRequest {
    backupId: string;
    backupTime: string;
    node: string;
    remote: string;
    nodesBackupRestoreRequest?: NodesBackupRestoreRequest;
}

export interface NodesPbsApiRunBackupRequest {
    node: string;
    remote: string;
    nodesBackupBackupRequest?: NodesBackupBackupRequest;
}

/**
 * 
 */
export class NodesPbsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTimer without sending the request
     */
    async createTimerRequestOpts(requestParameters: NodesPbsApiCreateTimerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling createTimer().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling createTimer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        // Optional body: only emit Content-Type when the body is actually provided.
        // PVE/PMG Perl HTTP server rejects empty bodies with Content-Type: application/json
        // ("malformed JSON string"), and other Proxmox products are equally fussy.
        if (requestParameters['nodesPbsCreateTimerRequest'] != null) {
            headerParameters['Content-Type'] = 'application/json';
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}/timer`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesPbsCreateTimerRequestToJSON(requestParameters['nodesPbsCreateTimerRequest']),
        };
    }

    /**
     * Create backup schedule
     * Create backup schedule
     */
    async createTimerRaw(requestParameters: NodesPbsApiCreateTimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsCreateTimerResponse>> {
        const requestOptions = await this.createTimerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsCreateTimerResponseFromJSON(jsonValue));
    }

    /**
     * Create backup schedule
     * Create backup schedule
     */
    async createTimer(requestParameters: NodesPbsApiCreateTimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsCreateTimerResponse> {
        const response = await this.createTimerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTimer without sending the request
     */
    async deleteTimerRequestOpts(requestParameters: NodesPbsApiDeleteTimerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling deleteTimer().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling deleteTimer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}/timer`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete backup schedule
     * Delete backup schedule
     */
    async deleteTimerRaw(requestParameters: NodesPbsApiDeleteTimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsDeleteTimerResponse>> {
        const requestOptions = await this.deleteTimerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsDeleteTimerResponseFromJSON(jsonValue));
    }

    /**
     * Delete backup schedule
     * Delete backup schedule
     */
    async deleteTimer(requestParameters: NodesPbsApiDeleteTimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsDeleteTimerResponse> {
        const response = await this.deleteTimerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for forgetSnapshot without sending the request
     */
    async forgetSnapshotRequestOpts(requestParameters: NodesPbsApiForgetSnapshotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling forgetSnapshot().'
            );
        }

        if (requestParameters['backupTime'] == null) {
            throw new runtime.RequiredError(
                'backupTime',
                'Required parameter "backupTime" was null or undefined when calling forgetSnapshot().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling forgetSnapshot().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling forgetSnapshot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}/snapshot/{backup-id}/{backup-time}`;
        urlPath = urlPath.replace('{backup-id}', encodeURIComponent(String(requestParameters['backupId'])));
        urlPath = urlPath.replace('{backup-time}', encodeURIComponent(String(requestParameters['backupTime'])));
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Forget a snapshot
     * Forget a snapshot
     */
    async forgetSnapshotRaw(requestParameters: NodesPbsApiForgetSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsForgetSnapshotResponse>> {
        const requestOptions = await this.forgetSnapshotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsForgetSnapshotResponseFromJSON(jsonValue));
    }

    /**
     * Forget a snapshot
     * Forget a snapshot
     */
    async forgetSnapshot(requestParameters: NodesPbsApiForgetSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsForgetSnapshotResponse> {
        const response = await this.forgetSnapshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupSnapshots without sending the request
     */
    async getGroupSnapshotsRequestOpts(requestParameters: NodesPbsApiGetGroupSnapshotsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling getGroupSnapshots().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getGroupSnapshots().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling getGroupSnapshots().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}/snapshot/{backup-id}`;
        urlPath = urlPath.replace('{backup-id}', encodeURIComponent(String(requestParameters['backupId'])));
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get snapshots from a specific ID stored on remote.
     * Get snapshots from a specific ID stored on remote
     */
    async getGroupSnapshotsRaw(requestParameters: NodesPbsApiGetGroupSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsGetGroupSnapshotsResponse>> {
        const requestOptions = await this.getGroupSnapshotsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsGetGroupSnapshotsResponseFromJSON(jsonValue));
    }

    /**
     * Get snapshots from a specific ID stored on remote.
     * Get snapshots from a specific ID stored on remote
     */
    async getGroupSnapshots(requestParameters: NodesPbsApiGetGroupSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsGetGroupSnapshotsResponse> {
        const response = await this.getGroupSnapshotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPbs without sending the request
     */
    async getPbsRequestOpts(requestParameters: NodesPbsApiGetPbsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getPbs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all configured Proxmox Backup Server jobs.
     * List all configured Proxmox Backup Server jobs
     */
    async getPbsRaw(requestParameters: NodesPbsApiGetPbsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsGetPbsResponse>> {
        const requestOptions = await this.getPbsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsGetPbsResponseFromJSON(jsonValue));
    }

    /**
     * List all configured Proxmox Backup Server jobs.
     * List all configured Proxmox Backup Server jobs
     */
    async getPbs(requestParameters: NodesPbsApiGetPbsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsGetPbsResponse> {
        const response = await this.getPbsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSnapshots without sending the request
     */
    async getSnapshotsRequestOpts(requestParameters: NodesPbsApiGetSnapshotsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getSnapshots().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling getSnapshots().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}/snapshot`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get snapshots stored on remote.
     * Get snapshots stored on remote
     */
    async getSnapshotsRaw(requestParameters: NodesPbsApiGetSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsGetSnapshotsResponse>> {
        const requestOptions = await this.getSnapshotsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsGetSnapshotsResponseFromJSON(jsonValue));
    }

    /**
     * Get snapshots stored on remote.
     * Get snapshots stored on remote
     */
    async getSnapshots(requestParameters: NodesPbsApiGetSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsGetSnapshotsResponse> {
        const response = await this.getSnapshotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTimer without sending the request
     */
    async listTimerRequestOpts(requestParameters: NodesPbsApiListTimerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling listTimer().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling listTimer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}/timer`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get timer specification
     * Get timer specification
     */
    async listTimerRaw(requestParameters: NodesPbsApiListTimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsListTimerResponse>> {
        const requestOptions = await this.listTimerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsListTimerResponseFromJSON(jsonValue));
    }

    /**
     * Get timer specification
     * Get timer specification
     */
    async listTimer(requestParameters: NodesPbsApiListTimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsListTimerResponse> {
        const response = await this.listTimerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for remoteIndex without sending the request
     */
    async remoteIndexRequestOpts(requestParameters: NodesPbsApiRemoteIndexRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling remoteIndex().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling remoteIndex().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Backup Job index.
     * Backup Job index
     */
    async remoteIndexRaw(requestParameters: NodesPbsApiRemoteIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsRemoteIndexResponse>> {
        const requestOptions = await this.remoteIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsRemoteIndexResponseFromJSON(jsonValue));
    }

    /**
     * Backup Job index.
     * Backup Job index
     */
    async remoteIndex(requestParameters: NodesPbsApiRemoteIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsRemoteIndexResponse> {
        const response = await this.remoteIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for restore without sending the request
     */
    async restoreRequestOpts(requestParameters: NodesPbsApiRestoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling restore().'
            );
        }

        if (requestParameters['backupTime'] == null) {
            throw new runtime.RequiredError(
                'backupTime',
                'Required parameter "backupTime" was null or undefined when calling restore().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling restore().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling restore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        // Optional body: only emit Content-Type when the body is actually provided.
        // PVE/PMG Perl HTTP server rejects empty bodies with Content-Type: application/json
        // ("malformed JSON string"), and other Proxmox products are equally fussy.
        if (requestParameters['nodesBackupRestoreRequest'] != null) {
            headerParameters['Content-Type'] = 'application/json';
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}/snapshot/{backup-id}/{backup-time}`;
        urlPath = urlPath.replace('{backup-id}', encodeURIComponent(String(requestParameters['backupId'])));
        urlPath = urlPath.replace('{backup-time}', encodeURIComponent(String(requestParameters['backupTime'])));
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesBackupRestoreRequestToJSON(requestParameters['nodesBackupRestoreRequest']),
        };
    }

    /**
     * Restore the system configuration.
     * Restore the system configuration
     */
    async restoreRaw(requestParameters: NodesPbsApiRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsRestoreResponse>> {
        const requestOptions = await this.restoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsRestoreResponseFromJSON(jsonValue));
    }

    /**
     * Restore the system configuration.
     * Restore the system configuration
     */
    async restore(requestParameters: NodesPbsApiRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsRestoreResponse> {
        const response = await this.restoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for runBackup without sending the request
     */
    async runBackupRequestOpts(requestParameters: NodesPbsApiRunBackupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling runBackup().'
            );
        }

        if (requestParameters['remote'] == null) {
            throw new runtime.RequiredError(
                'remote',
                'Required parameter "remote" was null or undefined when calling runBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        // Optional body: only emit Content-Type when the body is actually provided.
        // PVE/PMG Perl HTTP server rejects empty bodies with Content-Type: application/json
        // ("malformed JSON string"), and other Proxmox products are equally fussy.
        if (requestParameters['nodesBackupBackupRequest'] != null) {
            headerParameters['Content-Type'] = 'application/json';
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/pbs/{remote}/snapshot`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{remote}', encodeURIComponent(String(requestParameters['remote'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesBackupBackupRequestToJSON(requestParameters['nodesBackupBackupRequest']),
        };
    }

    /**
     * Create a new backup and prune the backup group afterwards, if configured.
     * Create a new backup and prune the backup group afterwards, if configured
     */
    async runBackupRaw(requestParameters: NodesPbsApiRunBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesPbsRunBackupResponse>> {
        const requestOptions = await this.runBackupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesPbsRunBackupResponseFromJSON(jsonValue));
    }

    /**
     * Create a new backup and prune the backup group afterwards, if configured.
     * Create a new backup and prune the backup group afterwards, if configured
     */
    async runBackup(requestParameters: NodesPbsApiRunBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesPbsRunBackupResponse> {
        const response = await this.runBackupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
