/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PmgError,
    PmgErrorFromJSON,
    PmgErrorToJSON,
} from '../models/PmgError';
import {
    type QuarantineBlacklistBlacklistAddRequest,
    QuarantineBlacklistBlacklistAddRequestFromJSON,
    QuarantineBlacklistBlacklistAddRequestToJSON,
} from '../models/QuarantineBlacklistBlacklistAddRequest';
import {
    type QuarantineWhitelistWhitelistAddResponse,
    QuarantineWhitelistWhitelistAddResponseFromJSON,
    QuarantineWhitelistWhitelistAddResponseToJSON,
} from '../models/QuarantineWhitelistWhitelistAddResponse';
import {
    type QuarantineWhitelistWhitelistDeleteBaseResponse,
    QuarantineWhitelistWhitelistDeleteBaseResponseFromJSON,
    QuarantineWhitelistWhitelistDeleteBaseResponseToJSON,
} from '../models/QuarantineWhitelistWhitelistDeleteBaseResponse';
import {
    type QuarantineWhitelistWhitelistResponse,
    QuarantineWhitelistWhitelistResponseFromJSON,
    QuarantineWhitelistWhitelistResponseToJSON,
} from '../models/QuarantineWhitelistWhitelistResponse';

export interface QuarantineWhitelistApiWhitelistRequest {
    pmail?: string;
}

export interface QuarantineWhitelistApiWhitelistAddRequest {
    quarantineBlacklistBlacklistAddRequest: QuarantineBlacklistBlacklistAddRequest;
}

export interface QuarantineWhitelistApiWhitelistDeleteBaseRequest {
    address: string;
    pmail?: string;
}

/**
 * 
 */
export class QuarantineWhitelistApi extends runtime.BaseAPI {

    /**
     * Creates request options for whitelist without sending the request
     */
    async whitelistRequestOpts(requestParameters: QuarantineWhitelistApiWhitelistRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['pmail'] != null) {
            queryParameters['pmail'] = requestParameters['pmail'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/quarantine/whitelist`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show user welcomelist.
     * Show user welcomelist
     */
    async whitelistRaw(requestParameters: QuarantineWhitelistApiWhitelistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuarantineWhitelistWhitelistResponse>> {
        const requestOptions = await this.whitelistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuarantineWhitelistWhitelistResponseFromJSON(jsonValue));
    }

    /**
     * Show user welcomelist.
     * Show user welcomelist
     */
    async whitelist(requestParameters: QuarantineWhitelistApiWhitelistRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuarantineWhitelistWhitelistResponse> {
        const response = await this.whitelistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for whitelistAdd without sending the request
     */
    async whitelistAddRequestOpts(requestParameters: QuarantineWhitelistApiWhitelistAddRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['quarantineBlacklistBlacklistAddRequest'] == null) {
            throw new runtime.RequiredError(
                'quarantineBlacklistBlacklistAddRequest',
                'Required parameter "quarantineBlacklistBlacklistAddRequest" was null or undefined when calling whitelistAdd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/quarantine/whitelist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuarantineBlacklistBlacklistAddRequestToJSON(requestParameters['quarantineBlacklistBlacklistAddRequest']),
        };
    }

    /**
     * Add user welcomelist entries.
     * Add user welcomelist entries
     */
    async whitelistAddRaw(requestParameters: QuarantineWhitelistApiWhitelistAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuarantineWhitelistWhitelistAddResponse>> {
        const requestOptions = await this.whitelistAddRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuarantineWhitelistWhitelistAddResponseFromJSON(jsonValue));
    }

    /**
     * Add user welcomelist entries.
     * Add user welcomelist entries
     */
    async whitelistAdd(requestParameters: QuarantineWhitelistApiWhitelistAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuarantineWhitelistWhitelistAddResponse> {
        const response = await this.whitelistAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for whitelistDeleteBase without sending the request
     */
    async whitelistDeleteBaseRequestOpts(requestParameters: QuarantineWhitelistApiWhitelistDeleteBaseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling whitelistDeleteBase().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['pmail'] != null) {
            queryParameters['pmail'] = requestParameters['pmail'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/quarantine/whitelist`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete user welcomelist entries.
     * Delete user welcomelist entries
     */
    async whitelistDeleteBaseRaw(requestParameters: QuarantineWhitelistApiWhitelistDeleteBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuarantineWhitelistWhitelistDeleteBaseResponse>> {
        const requestOptions = await this.whitelistDeleteBaseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuarantineWhitelistWhitelistDeleteBaseResponseFromJSON(jsonValue));
    }

    /**
     * Delete user welcomelist entries.
     * Delete user welcomelist entries
     */
    async whitelistDeleteBase(requestParameters: QuarantineWhitelistApiWhitelistDeleteBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuarantineWhitelistWhitelistDeleteBaseResponse> {
        const response = await this.whitelistDeleteBaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
