/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PmgError,
    PmgErrorFromJSON,
    PmgErrorToJSON,
} from '../models/PmgError';
import {
    type QuarantineBlacklistBlacklistAddRequest,
    QuarantineBlacklistBlacklistAddRequestFromJSON,
    QuarantineBlacklistBlacklistAddRequestToJSON,
} from '../models/QuarantineBlacklistBlacklistAddRequest';
import {
    type QuarantineWelcomelistWelcomelistAddResponse,
    QuarantineWelcomelistWelcomelistAddResponseFromJSON,
    QuarantineWelcomelistWelcomelistAddResponseToJSON,
} from '../models/QuarantineWelcomelistWelcomelistAddResponse';
import {
    type QuarantineWelcomelistWelcomelistDeleteBaseResponse,
    QuarantineWelcomelistWelcomelistDeleteBaseResponseFromJSON,
    QuarantineWelcomelistWelcomelistDeleteBaseResponseToJSON,
} from '../models/QuarantineWelcomelistWelcomelistDeleteBaseResponse';
import {
    type QuarantineWelcomelistWelcomelistResponse,
    QuarantineWelcomelistWelcomelistResponseFromJSON,
    QuarantineWelcomelistWelcomelistResponseToJSON,
} from '../models/QuarantineWelcomelistWelcomelistResponse';

export interface QuarantineWelcomelistApiWelcomelistRequest {
    pmail?: string;
}

export interface QuarantineWelcomelistApiWelcomelistAddRequest {
    quarantineBlacklistBlacklistAddRequest: QuarantineBlacklistBlacklistAddRequest;
}

export interface QuarantineWelcomelistApiWelcomelistDeleteBaseRequest {
    address: string;
    pmail?: string;
}

/**
 * 
 */
export class QuarantineWelcomelistApi extends runtime.BaseAPI {

    /**
     * Creates request options for welcomelist without sending the request
     */
    async welcomelistRequestOpts(requestParameters: QuarantineWelcomelistApiWelcomelistRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['pmail'] != null) {
            queryParameters['pmail'] = requestParameters['pmail'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/quarantine/welcomelist`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show user welcomelist.
     * Show user welcomelist
     */
    async welcomelistRaw(requestParameters: QuarantineWelcomelistApiWelcomelistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuarantineWelcomelistWelcomelistResponse>> {
        const requestOptions = await this.welcomelistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuarantineWelcomelistWelcomelistResponseFromJSON(jsonValue));
    }

    /**
     * Show user welcomelist.
     * Show user welcomelist
     */
    async welcomelist(requestParameters: QuarantineWelcomelistApiWelcomelistRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuarantineWelcomelistWelcomelistResponse> {
        const response = await this.welcomelistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for welcomelistAdd without sending the request
     */
    async welcomelistAddRequestOpts(requestParameters: QuarantineWelcomelistApiWelcomelistAddRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['quarantineBlacklistBlacklistAddRequest'] == null) {
            throw new runtime.RequiredError(
                'quarantineBlacklistBlacklistAddRequest',
                'Required parameter "quarantineBlacklistBlacklistAddRequest" was null or undefined when calling welcomelistAdd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/quarantine/welcomelist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuarantineBlacklistBlacklistAddRequestToJSON(requestParameters['quarantineBlacklistBlacklistAddRequest']),
        };
    }

    /**
     * Add user welcomelist entries.
     * Add user welcomelist entries
     */
    async welcomelistAddRaw(requestParameters: QuarantineWelcomelistApiWelcomelistAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuarantineWelcomelistWelcomelistAddResponse>> {
        const requestOptions = await this.welcomelistAddRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuarantineWelcomelistWelcomelistAddResponseFromJSON(jsonValue));
    }

    /**
     * Add user welcomelist entries.
     * Add user welcomelist entries
     */
    async welcomelistAdd(requestParameters: QuarantineWelcomelistApiWelcomelistAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuarantineWelcomelistWelcomelistAddResponse> {
        const response = await this.welcomelistAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for welcomelistDeleteBase without sending the request
     */
    async welcomelistDeleteBaseRequestOpts(requestParameters: QuarantineWelcomelistApiWelcomelistDeleteBaseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling welcomelistDeleteBase().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['pmail'] != null) {
            queryParameters['pmail'] = requestParameters['pmail'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/quarantine/welcomelist`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete user welcomelist entries.
     * Delete user welcomelist entries
     */
    async welcomelistDeleteBaseRaw(requestParameters: QuarantineWelcomelistApiWelcomelistDeleteBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuarantineWelcomelistWelcomelistDeleteBaseResponse>> {
        const requestOptions = await this.welcomelistDeleteBaseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuarantineWelcomelistWelcomelistDeleteBaseResponseFromJSON(jsonValue));
    }

    /**
     * Delete user welcomelist entries.
     * Delete user welcomelist entries
     */
    async welcomelistDeleteBase(requestParameters: QuarantineWelcomelistApiWelcomelistDeleteBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuarantineWelcomelistWelcomelistDeleteBaseResponse> {
        const response = await this.welcomelistDeleteBaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
