/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PmgError,
    PmgErrorFromJSON,
    PmgErrorToJSON,
} from '../models/PmgError';
import {
    type PmgStatisticsTypeEnum,
    PmgStatisticsTypeEnumFromJSON,
    PmgStatisticsTypeEnumToJSON,
} from '../models/PmgStatisticsTypeEnum';
import {
    type StatisticsContactResponse,
    StatisticsContactResponseFromJSON,
    StatisticsContactResponseToJSON,
} from '../models/StatisticsContactResponse';
import {
    type StatisticsDetailstatsResponse,
    StatisticsDetailstatsResponseFromJSON,
    StatisticsDetailstatsResponseToJSON,
} from '../models/StatisticsDetailstatsResponse';
import {
    type StatisticsDomainsResponse,
    StatisticsDomainsResponseFromJSON,
    StatisticsDomainsResponseToJSON,
} from '../models/StatisticsDomainsResponse';
import {
    type StatisticsGetStatisticsResponse,
    StatisticsGetStatisticsResponseFromJSON,
    StatisticsGetStatisticsResponseToJSON,
} from '../models/StatisticsGetStatisticsResponse';
import {
    type StatisticsMailResponse,
    StatisticsMailResponseFromJSON,
    StatisticsMailResponseToJSON,
} from '../models/StatisticsMailResponse';
import {
    type StatisticsMailcountResponse,
    StatisticsMailcountResponseFromJSON,
    StatisticsMailcountResponseToJSON,
} from '../models/StatisticsMailcountResponse';
import {
    type StatisticsMaildistributionResponse,
    StatisticsMaildistributionResponseFromJSON,
    StatisticsMaildistributionResponseToJSON,
} from '../models/StatisticsMaildistributionResponse';
import {
    type StatisticsReceiverResponse,
    StatisticsReceiverResponseFromJSON,
    StatisticsReceiverResponseToJSON,
} from '../models/StatisticsReceiverResponse';
import {
    type StatisticsRecentResponse,
    StatisticsRecentResponseFromJSON,
    StatisticsRecentResponseToJSON,
} from '../models/StatisticsRecentResponse';
import {
    type StatisticsRecentreceiversResponse,
    StatisticsRecentreceiversResponseFromJSON,
    StatisticsRecentreceiversResponseToJSON,
} from '../models/StatisticsRecentreceiversResponse';
import {
    type StatisticsRejectcountResponse,
    StatisticsRejectcountResponseFromJSON,
    StatisticsRejectcountResponseToJSON,
} from '../models/StatisticsRejectcountResponse';
import {
    type StatisticsSenderResponse,
    StatisticsSenderResponseFromJSON,
    StatisticsSenderResponseToJSON,
} from '../models/StatisticsSenderResponse';
import {
    type StatisticsSpamscoresResponse,
    StatisticsSpamscoresResponseFromJSON,
    StatisticsSpamscoresResponseToJSON,
} from '../models/StatisticsSpamscoresResponse';
import {
    type StatisticsVirusResponse,
    StatisticsVirusResponseFromJSON,
    StatisticsVirusResponseToJSON,
} from '../models/StatisticsVirusResponse';

export interface StatisticsApiContactRequest {
    day?: number;
    endtime?: number;
    filter?: string;
    month?: number;
    orderby?: string;
    starttime?: number;
    year?: number;
}

export interface StatisticsApiDetailstatsRequest {
    address: string;
    type: PmgStatisticsTypeEnum;
    day?: number;
    endtime?: number;
    filter?: string;
    month?: number;
    orderby?: string;
    starttime?: number;
    year?: number;
}

export interface StatisticsApiDomainsRequest {
    day?: number;
    endtime?: number;
    month?: number;
    starttime?: number;
    year?: number;
}

export interface StatisticsApiMailRequest {
    day?: number;
    endtime?: number;
    month?: number;
    starttime?: number;
    year?: number;
}

export interface StatisticsApiMailcountRequest {
    day?: number;
    endtime?: number;
    month?: number;
    starttime?: number;
    timespan?: number;
    year?: number;
}

export interface StatisticsApiMaildistributionRequest {
    day?: number;
    endtime?: number;
    month?: number;
    starttime?: number;
    year?: number;
}

export interface StatisticsApiReceiverRequest {
    day?: number;
    endtime?: number;
    filter?: string;
    month?: number;
    orderby?: string;
    starttime?: number;
    year?: number;
}

export interface StatisticsApiRecentRequest {
    hours?: number;
    timespan?: number;
}

export interface StatisticsApiRecentreceiversRequest {
    hours?: number;
    limit?: number;
}

export interface StatisticsApiRejectcountRequest {
    day?: number;
    endtime?: number;
    month?: number;
    starttime?: number;
    timespan?: number;
    year?: number;
}

export interface StatisticsApiSenderRequest {
    day?: number;
    endtime?: number;
    filter?: string;
    month?: number;
    orderby?: string;
    starttime?: number;
    year?: number;
}

export interface StatisticsApiSpamscoresRequest {
    day?: number;
    endtime?: number;
    month?: number;
    starttime?: number;
    year?: number;
}

export interface StatisticsApiVirusRequest {
    day?: number;
    endtime?: number;
    month?: number;
    starttime?: number;
    year?: number;
}

/**
 * 
 */
export class StatisticsApi extends runtime.BaseAPI {

    /**
     * Creates request options for contact without sending the request
     */
    async contactRequestOpts(requestParameters: StatisticsApiContactRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['orderby'] != null) {
            queryParameters['orderby'] = requestParameters['orderby'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/contact`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Contact Address Statistics.
     * Contact Address Statistics
     */
    async contactRaw(requestParameters: StatisticsApiContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsContactResponse>> {
        const requestOptions = await this.contactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsContactResponseFromJSON(jsonValue));
    }

    /**
     * Contact Address Statistics.
     * Contact Address Statistics
     */
    async contact(requestParameters: StatisticsApiContactRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsContactResponse> {
        const response = await this.contactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for detailstats without sending the request
     */
    async detailstatsRequestOpts(requestParameters: StatisticsApiDetailstatsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling detailstats().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling detailstats().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['orderby'] != null) {
            queryParameters['orderby'] = requestParameters['orderby'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/detail`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detailed Statistics.
     * Detailed Statistics
     */
    async detailstatsRaw(requestParameters: StatisticsApiDetailstatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsDetailstatsResponse>> {
        const requestOptions = await this.detailstatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsDetailstatsResponseFromJSON(jsonValue));
    }

    /**
     * Detailed Statistics.
     * Detailed Statistics
     */
    async detailstats(requestParameters: StatisticsApiDetailstatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsDetailstatsResponse> {
        const response = await this.detailstatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for domains without sending the request
     */
    async domainsRequestOpts(requestParameters: StatisticsApiDomainsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/domains`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mail Domains Statistics.
     * Mail Domains Statistics
     */
    async domainsRaw(requestParameters: StatisticsApiDomainsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsDomainsResponse>> {
        const requestOptions = await this.domainsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsDomainsResponseFromJSON(jsonValue));
    }

    /**
     * Mail Domains Statistics.
     * Mail Domains Statistics
     */
    async domains(requestParameters: StatisticsApiDomainsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsDomainsResponse> {
        const response = await this.domainsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStatistics without sending the request
     */
    async getStatisticsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Directory index.
     * Directory index
     */
    async getStatisticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsGetStatisticsResponse>> {
        const requestOptions = await this.getStatisticsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsGetStatisticsResponseFromJSON(jsonValue));
    }

    /**
     * Directory index.
     * Directory index
     */
    async getStatistics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsGetStatisticsResponse> {
        const response = await this.getStatisticsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mail without sending the request
     */
    async mailRequestOpts(requestParameters: StatisticsApiMailRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/mail`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * General Mail Statistics.
     * General Mail Statistics
     */
    async mailRaw(requestParameters: StatisticsApiMailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsMailResponse>> {
        const requestOptions = await this.mailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsMailResponseFromJSON(jsonValue));
    }

    /**
     * General Mail Statistics.
     * General Mail Statistics
     */
    async mail(requestParameters: StatisticsApiMailRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsMailResponse> {
        const response = await this.mailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mailcount without sending the request
     */
    async mailcountRequestOpts(requestParameters: StatisticsApiMailcountRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['timespan'] != null) {
            queryParameters['timespan'] = requestParameters['timespan'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/mailcount`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mail Count Statistics.
     * Mail Count Statistics
     */
    async mailcountRaw(requestParameters: StatisticsApiMailcountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsMailcountResponse>> {
        const requestOptions = await this.mailcountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsMailcountResponseFromJSON(jsonValue));
    }

    /**
     * Mail Count Statistics.
     * Mail Count Statistics
     */
    async mailcount(requestParameters: StatisticsApiMailcountRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsMailcountResponse> {
        const response = await this.mailcountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for maildistribution without sending the request
     */
    async maildistributionRequestOpts(requestParameters: StatisticsApiMaildistributionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/maildistribution`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the count of spam mails grouped by spam score. Count for score 10 includes mails with spam score > 10.
     * Get the count of spam mails grouped by spam score
     */
    async maildistributionRaw(requestParameters: StatisticsApiMaildistributionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsMaildistributionResponse>> {
        const requestOptions = await this.maildistributionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsMaildistributionResponseFromJSON(jsonValue));
    }

    /**
     * Get the count of spam mails grouped by spam score. Count for score 10 includes mails with spam score > 10.
     * Get the count of spam mails grouped by spam score
     */
    async maildistribution(requestParameters: StatisticsApiMaildistributionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsMaildistributionResponse> {
        const response = await this.maildistributionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiver without sending the request
     */
    async receiverRequestOpts(requestParameters: StatisticsApiReceiverRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['orderby'] != null) {
            queryParameters['orderby'] = requestParameters['orderby'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/receiver`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Receiver Address Statistics.
     * Receiver Address Statistics
     */
    async receiverRaw(requestParameters: StatisticsApiReceiverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsReceiverResponse>> {
        const requestOptions = await this.receiverRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsReceiverResponseFromJSON(jsonValue));
    }

    /**
     * Receiver Address Statistics.
     * Receiver Address Statistics
     */
    async receiver(requestParameters: StatisticsApiReceiverRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsReceiverResponse> {
        const response = await this.receiverRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recent without sending the request
     */
    async recentRequestOpts(requestParameters: StatisticsApiRecentRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['hours'] != null) {
            queryParameters['hours'] = requestParameters['hours'];
        }

        if (requestParameters['timespan'] != null) {
            queryParameters['timespan'] = requestParameters['timespan'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/recent`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mail Count Statistics.
     * Mail Count Statistics
     */
    async recentRaw(requestParameters: StatisticsApiRecentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsRecentResponse>> {
        const requestOptions = await this.recentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsRecentResponseFromJSON(jsonValue));
    }

    /**
     * Mail Count Statistics.
     * Mail Count Statistics
     */
    async recent(requestParameters: StatisticsApiRecentRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsRecentResponse> {
        const response = await this.recentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recentreceivers without sending the request
     */
    async recentreceiversRequestOpts(requestParameters: StatisticsApiRecentreceiversRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['hours'] != null) {
            queryParameters['hours'] = requestParameters['hours'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/recentreceivers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Top recent Mail Receivers (including spam)
     * Top recent Mail Receivers (including spam)
     */
    async recentreceiversRaw(requestParameters: StatisticsApiRecentreceiversRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsRecentreceiversResponse>> {
        const requestOptions = await this.recentreceiversRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsRecentreceiversResponseFromJSON(jsonValue));
    }

    /**
     * Top recent Mail Receivers (including spam)
     * Top recent Mail Receivers (including spam)
     */
    async recentreceivers(requestParameters: StatisticsApiRecentreceiversRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsRecentreceiversResponse> {
        const response = await this.recentreceiversRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rejectcount without sending the request
     */
    async rejectcountRequestOpts(requestParameters: StatisticsApiRejectcountRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['timespan'] != null) {
            queryParameters['timespan'] = requestParameters['timespan'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/rejectcount`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Early SMTP reject count statistic (RBL, PREGREET rejects with postscreen)
     * Early SMTP reject count statistic (RBL, PREGREET rejects with postscreen)
     */
    async rejectcountRaw(requestParameters: StatisticsApiRejectcountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsRejectcountResponse>> {
        const requestOptions = await this.rejectcountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsRejectcountResponseFromJSON(jsonValue));
    }

    /**
     * Early SMTP reject count statistic (RBL, PREGREET rejects with postscreen)
     * Early SMTP reject count statistic (RBL, PREGREET rejects with postscreen)
     */
    async rejectcount(requestParameters: StatisticsApiRejectcountRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsRejectcountResponse> {
        const response = await this.rejectcountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sender without sending the request
     */
    async senderRequestOpts(requestParameters: StatisticsApiSenderRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['orderby'] != null) {
            queryParameters['orderby'] = requestParameters['orderby'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/sender`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sender Address Statistics.
     * Sender Address Statistics
     */
    async senderRaw(requestParameters: StatisticsApiSenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsSenderResponse>> {
        const requestOptions = await this.senderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsSenderResponseFromJSON(jsonValue));
    }

    /**
     * Sender Address Statistics.
     * Sender Address Statistics
     */
    async sender(requestParameters: StatisticsApiSenderRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsSenderResponse> {
        const response = await this.senderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for spamscores without sending the request
     */
    async spamscoresRequestOpts(requestParameters: StatisticsApiSpamscoresRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/spamscores`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the count of spam mails grouped by spam score. Count for score 10 includes mails with spam score > 10.
     * Get the count of spam mails grouped by spam score
     */
    async spamscoresRaw(requestParameters: StatisticsApiSpamscoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsSpamscoresResponse>> {
        const requestOptions = await this.spamscoresRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsSpamscoresResponseFromJSON(jsonValue));
    }

    /**
     * Get the count of spam mails grouped by spam score. Count for score 10 includes mails with spam score > 10.
     * Get the count of spam mails grouped by spam score
     */
    async spamscores(requestParameters: StatisticsApiSpamscoresRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsSpamscoresResponse> {
        const response = await this.spamscoresRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for virus without sending the request
     */
    async virusRequestOpts(requestParameters: StatisticsApiVirusRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['endtime'] != null) {
            queryParameters['endtime'] = requestParameters['endtime'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['starttime'] != null) {
            queryParameters['starttime'] = requestParameters['starttime'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PMGApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/statistics/virus`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Statistics about detected Viruses.
     * Get Statistics about detected Viruses
     */
    async virusRaw(requestParameters: StatisticsApiVirusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticsVirusResponse>> {
        const requestOptions = await this.virusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsVirusResponseFromJSON(jsonValue));
    }

    /**
     * Get Statistics about detected Viruses.
     * Get Statistics about detected Viruses
     */
    async virus(requestParameters: StatisticsApiVirusRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticsVirusResponse> {
        const response = await this.virusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
