/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessTicketCreateTicketRequest
 */
export interface AccessTicketCreateTicketRequest {

    /**
     * One-time password for Two-factor authentication.
     * @type {string}
     * @memberof AccessTicketCreateTicketRequest
     */
    otp?: string;

    /**
     * The secret password. This can also be a valid ticket.
     * @type {string}
     * @memberof AccessTicketCreateTicketRequest
     */
    password: string;

    /**
     * Verify ticket, and check if user have access on 'path'
     * @type {string}
     * @memberof AccessTicketCreateTicketRequest
     */
    path?: string;

    /**
     * You can optionally pass the realm using this parameter. Normally the realm is simply added to the username <username>@<relam>.
     * @type {string}
     * @memberof AccessTicketCreateTicketRequest
     */
    realm?: string;

    /**
     * The signed TFA challenge string the user wants to respond to.
     * @type {string}
     * @memberof AccessTicketCreateTicketRequest
     */
    tfaChallenge?: string;

    /**
     * User name
     * @type {string}
     * @memberof AccessTicketCreateTicketRequest
     */
    username: string;

}

/**
 * Check if a given object implements the AccessTicketCreateTicketRequest interface.
 */
export function instanceOfAccessTicketCreateTicketRequest(value: object): value is AccessTicketCreateTicketRequest {
    
    
    if (!('password' in value) || value['password'] === undefined) return false;
    
    
    
    
    if (!('username' in value) || value['username'] === undefined) return false;
    
    return true;
}

export function AccessTicketCreateTicketRequestFromJSON(json: any): AccessTicketCreateTicketRequest {
    return AccessTicketCreateTicketRequestFromJSONTyped(json, false);
}

export function AccessTicketCreateTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTicketCreateTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'otp': json['otp'] == null ? undefined : json['otp'],
        
        'password': json['password'],
        
        'path': json['path'] == null ? undefined : json['path'],
        
        'realm': json['realm'] == null ? undefined : json['realm'],
        
        'tfaChallenge': json['tfa-challenge'] == null ? undefined : json['tfa-challenge'],
        
        'username': json['username'],
        
    };
}

export function AccessTicketCreateTicketRequestToJSON(json: any): AccessTicketCreateTicketRequest {
    return AccessTicketCreateTicketRequestToJSONTyped(json, false);
}

export function AccessTicketCreateTicketRequestToJSONTyped(value?: AccessTicketCreateTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'otp': value['otp'],
        
        'password': value['password'],
        
        'path': value['path'],
        
        'realm': value['realm'],
        
        'tfa-challenge': value['tfaChallenge'],
        
        'username': value['username'],
        
    };
}

