/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuledbGetConfigResponseData
 */
export interface ConfigRuledbGetConfigResponseData {

    /**
     * 
     * @type {number}
     * @memberof ConfigRuledbGetConfigResponseData
     */
    id: number;

    /**
     * 
     * @type {string}
     * @memberof ConfigRuledbGetConfigResponseData
     */
    info: string;

    /**
     * 
     * @type {string}
     * @memberof ConfigRuledbGetConfigResponseData
     */
    name: string;

}

/**
 * Check if a given object implements the ConfigRuledbGetConfigResponseData interface.
 */
export function instanceOfConfigRuledbGetConfigResponseData(value: object): value is ConfigRuledbGetConfigResponseData {
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('info' in value) || value['info'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbGetConfigResponseDataFromJSON(json: any): ConfigRuledbGetConfigResponseData {
    return ConfigRuledbGetConfigResponseDataFromJSONTyped(json, false);
}

export function ConfigRuledbGetConfigResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbGetConfigResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'id': json['id'],
        
        'info': json['info'],
        
        'name': json['name'],
        
    };
}

export function ConfigRuledbGetConfigResponseDataToJSON(json: any): ConfigRuledbGetConfigResponseData {
    return ConfigRuledbGetConfigResponseDataToJSONTyped(json, false);
}

export function ConfigRuledbGetConfigResponseDataToJSONTyped(value?: ConfigRuledbGetConfigResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'id': value['id'],
        
        'info': value['info'],
        
        'name': value['name'],
        
    };
}

