/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigWelcomelistUpdateReceiverDomainResponse
 */
export interface ConfigWelcomelistUpdateReceiverDomainResponse {

    /**
     * 
     * @type {any}
     * @memberof ConfigWelcomelistUpdateReceiverDomainResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigWelcomelistUpdateReceiverDomainResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigWelcomelistUpdateReceiverDomainResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigWelcomelistUpdateReceiverDomainResponse interface.
 */
export function instanceOfConfigWelcomelistUpdateReceiverDomainResponse(value: object): value is ConfigWelcomelistUpdateReceiverDomainResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigWelcomelistUpdateReceiverDomainResponseFromJSON(json: any): ConfigWelcomelistUpdateReceiverDomainResponse {
    return ConfigWelcomelistUpdateReceiverDomainResponseFromJSONTyped(json, false);
}

export function ConfigWelcomelistUpdateReceiverDomainResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigWelcomelistUpdateReceiverDomainResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigWelcomelistUpdateReceiverDomainResponseToJSON(json: any): ConfigWelcomelistUpdateReceiverDomainResponse {
    return ConfigWelcomelistUpdateReceiverDomainResponseToJSONTyped(json, false);
}

export function ConfigWelcomelistUpdateReceiverDomainResponseToJSONTyped(value?: ConfigWelcomelistUpdateReceiverDomainResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

