/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface ConfigRuledbUpdateNotificationRequest
 */
export interface ConfigRuledbUpdateNotificationRequest {

    /**
     * Attach original E-Mail
     * @type {PmgBoolean}
     * @memberof ConfigRuledbUpdateNotificationRequest
     */
    attach?: PmgBoolean;

    /**
     * The Notification Body
     * @type {string}
     * @memberof ConfigRuledbUpdateNotificationRequest
     */
    body: string;

    /**
     * Informational comment.
     * @type {string}
     * @memberof ConfigRuledbUpdateNotificationRequest
     */
    info?: string;

    /**
     * Action name.
     * @type {string}
     * @memberof ConfigRuledbUpdateNotificationRequest
     */
    name?: string;

    /**
     * The Notification subject
     * @type {string}
     * @memberof ConfigRuledbUpdateNotificationRequest
     */
    subject: string;

    /**
     * The Receiver E-Mail address
     * @type {string}
     * @memberof ConfigRuledbUpdateNotificationRequest
     */
    to: string;

}



/**
 * Check if a given object implements the ConfigRuledbUpdateNotificationRequest interface.
 */
export function instanceOfConfigRuledbUpdateNotificationRequest(value: object): value is ConfigRuledbUpdateNotificationRequest {
    
    
    if (!('body' in value) || value['body'] === undefined) return false;
    
    
    
    if (!('subject' in value) || value['subject'] === undefined) return false;
    
    if (!('to' in value) || value['to'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbUpdateNotificationRequestFromJSON(json: any): ConfigRuledbUpdateNotificationRequest {
    return ConfigRuledbUpdateNotificationRequestFromJSONTyped(json, false);
}

export function ConfigRuledbUpdateNotificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbUpdateNotificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'attach': json['attach'] == null ? undefined : PmgBooleanFromJSON(json['attach']),
        
        'body': json['body'],
        
        'info': json['info'] == null ? undefined : json['info'],
        
        'name': json['name'] == null ? undefined : json['name'],
        
        'subject': json['subject'],
        
        'to': json['to'],
        
    };
}

export function ConfigRuledbUpdateNotificationRequestToJSON(json: any): ConfigRuledbUpdateNotificationRequest {
    return ConfigRuledbUpdateNotificationRequestToJSONTyped(json, false);
}

export function ConfigRuledbUpdateNotificationRequestToJSONTyped(value?: ConfigRuledbUpdateNotificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'attach': PmgBooleanToJSON(value['attach']),
        
        'body': value['body'],
        
        'info': value['info'],
        
        'name': value['name'],
        
        'subject': value['subject'],
        
        'to': value['to'],
        
    };
}

