/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigAcmeGetAcmeResponseDataInner } from './ConfigAcmeGetAcmeResponseDataInner';
import {
    ConfigAcmeGetAcmeResponseDataInnerFromJSON,
    ConfigAcmeGetAcmeResponseDataInnerFromJSONTyped,
    ConfigAcmeGetAcmeResponseDataInnerToJSON,
    ConfigAcmeGetAcmeResponseDataInnerToJSONTyped,
} from './ConfigAcmeGetAcmeResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigAcmeAccountIndexResponse
 */
export interface ConfigAcmeAccountIndexResponse {

    /**
     * 
     * @type {Array<ConfigAcmeGetAcmeResponseDataInner>}
     * @memberof ConfigAcmeAccountIndexResponse
     */
    data: Array<ConfigAcmeGetAcmeResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigAcmeAccountIndexResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigAcmeAccountIndexResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigAcmeAccountIndexResponse interface.
 */
export function instanceOfConfigAcmeAccountIndexResponse(value: object): value is ConfigAcmeAccountIndexResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigAcmeAccountIndexResponseFromJSON(json: any): ConfigAcmeAccountIndexResponse {
    return ConfigAcmeAccountIndexResponseFromJSONTyped(json, false);
}

export function ConfigAcmeAccountIndexResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAcmeAccountIndexResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigAcmeGetAcmeResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigAcmeAccountIndexResponseToJSON(json: any): ConfigAcmeAccountIndexResponse {
    return ConfigAcmeAccountIndexResponseToJSONTyped(json, false);
}

export function ConfigAcmeAccountIndexResponseToJSONTyped(value?: ConfigAcmeAccountIndexResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigAcmeGetAcmeResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

