/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigClusterNodesResponseDataInner } from './ConfigClusterNodesResponseDataInner';
import {
    ConfigClusterNodesResponseDataInnerFromJSON,
    ConfigClusterNodesResponseDataInnerFromJSONTyped,
    ConfigClusterNodesResponseDataInnerToJSON,
    ConfigClusterNodesResponseDataInnerToJSONTyped,
} from './ConfigClusterNodesResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigClusterNodesResponse
 */
export interface ConfigClusterNodesResponse {

    /**
     * 
     * @type {Array<ConfigClusterNodesResponseDataInner>}
     * @memberof ConfigClusterNodesResponse
     */
    data: Array<ConfigClusterNodesResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigClusterNodesResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigClusterNodesResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigClusterNodesResponse interface.
 */
export function instanceOfConfigClusterNodesResponse(value: object): value is ConfigClusterNodesResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigClusterNodesResponseFromJSON(json: any): ConfigClusterNodesResponse {
    return ConfigClusterNodesResponseFromJSONTyped(json, false);
}

export function ConfigClusterNodesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigClusterNodesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigClusterNodesResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigClusterNodesResponseToJSON(json: any): ConfigClusterNodesResponse {
    return ConfigClusterNodesResponseToJSONTyped(json, false);
}

export function ConfigClusterNodesResponseToJSONTyped(value?: ConfigClusterNodesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigClusterNodesResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

