/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigRuledbListActionsResponseDataInner } from './ConfigRuledbListActionsResponseDataInner';
import {
    ConfigRuledbListActionsResponseDataInnerFromJSON,
    ConfigRuledbListActionsResponseDataInnerFromJSONTyped,
    ConfigRuledbListActionsResponseDataInnerToJSON,
    ConfigRuledbListActionsResponseDataInnerToJSONTyped,
} from './ConfigRuledbListActionsResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigRuledbListActionsResponse
 */
export interface ConfigRuledbListActionsResponse {

    /**
     * 
     * @type {Array<ConfigRuledbListActionsResponseDataInner>}
     * @memberof ConfigRuledbListActionsResponse
     */
    data: Array<ConfigRuledbListActionsResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbListActionsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbListActionsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbListActionsResponse interface.
 */
export function instanceOfConfigRuledbListActionsResponse(value: object): value is ConfigRuledbListActionsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbListActionsResponseFromJSON(json: any): ConfigRuledbListActionsResponse {
    return ConfigRuledbListActionsResponseFromJSONTyped(json, false);
}

export function ConfigRuledbListActionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbListActionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigRuledbListActionsResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbListActionsResponseToJSON(json: any): ConfigRuledbListActionsResponse {
    return ConfigRuledbListActionsResponseToJSONTyped(json, false);
}

export function ConfigRuledbListActionsResponseToJSONTyped(value?: ConfigRuledbListActionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigRuledbListActionsResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

