/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuledbVirusfilterResponse
 */
export interface ConfigRuledbVirusfilterResponse {

    /**
     * 
     * @type {number}
     * @memberof ConfigRuledbVirusfilterResponse
     */
    data: bigint | string | number;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbVirusfilterResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbVirusfilterResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbVirusfilterResponse interface.
 */
export function instanceOfConfigRuledbVirusfilterResponse(value: object): value is ConfigRuledbVirusfilterResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbVirusfilterResponseFromJSON(json: any): ConfigRuledbVirusfilterResponse {
    return ConfigRuledbVirusfilterResponseFromJSONTyped(json, false);
}

export function ConfigRuledbVirusfilterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbVirusfilterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': BigInt(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbVirusfilterResponseToJSON(json: any): ConfigRuledbVirusfilterResponse {
    return ConfigRuledbVirusfilterResponseToJSONTyped(json, false);
}

export function ConfigRuledbVirusfilterResponseToJSONTyped(value?: ConfigRuledbVirusfilterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': String(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

