/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface ConfigRuledbUpdateBccRequest
 */
export interface ConfigRuledbUpdateBccRequest {

    /**
     * Informational comment.
     * @type {string}
     * @memberof ConfigRuledbUpdateBccRequest
     */
    info?: string;

    /**
     * Action name.
     * @type {string}
     * @memberof ConfigRuledbUpdateBccRequest
     */
    name?: string;

    /**
     * Send the original, unmodified mail.
     * @type {PmgBoolean}
     * @memberof ConfigRuledbUpdateBccRequest
     */
    original?: PmgBoolean;

    /**
     * Send a Blind Carbon Copy to this email address.
     * @type {string}
     * @memberof ConfigRuledbUpdateBccRequest
     */
    target: string;

}



/**
 * Check if a given object implements the ConfigRuledbUpdateBccRequest interface.
 */
export function instanceOfConfigRuledbUpdateBccRequest(value: object): value is ConfigRuledbUpdateBccRequest {
    
    
    
    
    if (!('target' in value) || value['target'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbUpdateBccRequestFromJSON(json: any): ConfigRuledbUpdateBccRequest {
    return ConfigRuledbUpdateBccRequestFromJSONTyped(json, false);
}

export function ConfigRuledbUpdateBccRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbUpdateBccRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'info': json['info'] == null ? undefined : json['info'],
        
        'name': json['name'] == null ? undefined : json['name'],
        
        'original': json['original'] == null ? undefined : PmgBooleanFromJSON(json['original']),
        
        'target': json['target'],
        
    };
}

export function ConfigRuledbUpdateBccRequestToJSON(json: any): ConfigRuledbUpdateBccRequest {
    return ConfigRuledbUpdateBccRequestToJSONTyped(json, false);
}

export function ConfigRuledbUpdateBccRequestToJSONTyped(value?: ConfigRuledbUpdateBccRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'info': value['info'],
        
        'name': value['name'],
        
        'original': PmgBooleanToJSON(value['original']),
        
        'target': value['target'],
        
    };
}

