/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgApiEnum } from './PmgApiEnum';
import {
    PmgApiEnumFromJSON,
    PmgApiEnumFromJSONTyped,
    PmgApiEnumToJSON,
    PmgApiEnumToJSONTyped,
} from './PmgApiEnum';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface ConfigAcmeUpdatePluginRequest
 */
export interface ConfigAcmeUpdatePluginRequest {

    /**
     * API plugin name
     * @type {PmgApiEnum}
     * @memberof ConfigAcmeUpdatePluginRequest
     */
    api?: PmgApiEnum;

    /**
     * DNS plugin data. (base64 encoded)
     * @type {string}
     * @memberof ConfigAcmeUpdatePluginRequest
     */
    data?: string;

    /**
     * A list of settings you want to delete.
     * @type {string}
     * @memberof ConfigAcmeUpdatePluginRequest
     */
    _delete?: string;

    /**
     * Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ConfigAcmeUpdatePluginRequest
     */
    digest?: string;

    /**
     * Flag to disable the config.
     * @type {PmgBoolean}
     * @memberof ConfigAcmeUpdatePluginRequest
     */
    disable?: PmgBoolean;

    /**
     * List of cluster node names.
     * @type {string}
     * @memberof ConfigAcmeUpdatePluginRequest
     */
    nodes?: string;

    /**
     * Extra delay in seconds to wait before requesting validation. Allows to cope with a long TTL of DNS records.
     * @type {number}
     * @memberof ConfigAcmeUpdatePluginRequest
     */
    validationDelay?: number;

}



/**
 * Check if a given object implements the ConfigAcmeUpdatePluginRequest interface.
 */
export function instanceOfConfigAcmeUpdatePluginRequest(value: object): value is ConfigAcmeUpdatePluginRequest {
    
    
    
    
    
    
    
    
    return true;
}

export function ConfigAcmeUpdatePluginRequestFromJSON(json: any): ConfigAcmeUpdatePluginRequest {
    return ConfigAcmeUpdatePluginRequestFromJSONTyped(json, false);
}

export function ConfigAcmeUpdatePluginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAcmeUpdatePluginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'api': json['api'] == null ? undefined : PmgApiEnumFromJSON(json['api']),
        
        'data': json['data'] == null ? undefined : json['data'],
        
        '_delete': json['delete'] == null ? undefined : json['delete'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'disable': json['disable'] == null ? undefined : PmgBooleanFromJSON(json['disable']),
        
        'nodes': json['nodes'] == null ? undefined : json['nodes'],
        
        'validationDelay': json['validation-delay'] == null ? undefined : json['validation-delay'],
        
    };
}

export function ConfigAcmeUpdatePluginRequestToJSON(json: any): ConfigAcmeUpdatePluginRequest {
    return ConfigAcmeUpdatePluginRequestToJSONTyped(json, false);
}

export function ConfigAcmeUpdatePluginRequestToJSONTyped(value?: ConfigAcmeUpdatePluginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'api': PmgApiEnumToJSON(value['api']),
        
        'data': value['data'],
        
        'delete': value['_delete'],
        
        'digest': value['digest'],
        
        'disable': PmgBooleanToJSON(value['disable']),
        
        'nodes': value['nodes'],
        
        'validation-delay': value['validationDelay'],
        
    };
}

