/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigTransportGetTransportResponseDataInner } from './ConfigTransportGetTransportResponseDataInner';
import {
    ConfigTransportGetTransportResponseDataInnerFromJSON,
    ConfigTransportGetTransportResponseDataInnerFromJSONTyped,
    ConfigTransportGetTransportResponseDataInnerToJSON,
    ConfigTransportGetTransportResponseDataInnerToJSONTyped,
} from './ConfigTransportGetTransportResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigTransportGetTransportResponse
 */
export interface ConfigTransportGetTransportResponse {

    /**
     * 
     * @type {Array<ConfigTransportGetTransportResponseDataInner>}
     * @memberof ConfigTransportGetTransportResponse
     */
    data: Array<ConfigTransportGetTransportResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigTransportGetTransportResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigTransportGetTransportResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigTransportGetTransportResponse interface.
 */
export function instanceOfConfigTransportGetTransportResponse(value: object): value is ConfigTransportGetTransportResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigTransportGetTransportResponseFromJSON(json: any): ConfigTransportGetTransportResponse {
    return ConfigTransportGetTransportResponseFromJSONTyped(json, false);
}

export function ConfigTransportGetTransportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTransportGetTransportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigTransportGetTransportResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigTransportGetTransportResponseToJSON(json: any): ConfigTransportGetTransportResponse {
    return ConfigTransportGetTransportResponseToJSONTyped(json, false);
}

export function ConfigTransportGetTransportResponseToJSONTyped(value?: ConfigTransportGetTransportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigTransportGetTransportResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

