/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface ConfigRuledbCreateWhatGroupRequest
 */
export interface ConfigRuledbCreateWhatGroupRequest {

    /**
     * If set to 1, objects in this group are 'and' combined.
     * @type {PmgBoolean}
     * @memberof ConfigRuledbCreateWhatGroupRequest
     */
    and?: PmgBoolean;

    /**
     * Informational comment.
     * @type {string}
     * @memberof ConfigRuledbCreateWhatGroupRequest
     */
    info?: string;

    /**
     * If set to 1, the resulting match is inverted.
     * @type {PmgBoolean}
     * @memberof ConfigRuledbCreateWhatGroupRequest
     */
    invert?: PmgBoolean;

    /**
     * Group name.
     * @type {string}
     * @memberof ConfigRuledbCreateWhatGroupRequest
     */
    name: string;

}



/**
 * Check if a given object implements the ConfigRuledbCreateWhatGroupRequest interface.
 */
export function instanceOfConfigRuledbCreateWhatGroupRequest(value: object): value is ConfigRuledbCreateWhatGroupRequest {
    
    
    
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbCreateWhatGroupRequestFromJSON(json: any): ConfigRuledbCreateWhatGroupRequest {
    return ConfigRuledbCreateWhatGroupRequestFromJSONTyped(json, false);
}

export function ConfigRuledbCreateWhatGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbCreateWhatGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'and': json['and'] == null ? undefined : PmgBooleanFromJSON(json['and']),
        
        'info': json['info'] == null ? undefined : json['info'],
        
        'invert': json['invert'] == null ? undefined : PmgBooleanFromJSON(json['invert']),
        
        'name': json['name'],
        
    };
}

export function ConfigRuledbCreateWhatGroupRequestToJSON(json: any): ConfigRuledbCreateWhatGroupRequest {
    return ConfigRuledbCreateWhatGroupRequestToJSONTyped(json, false);
}

export function ConfigRuledbCreateWhatGroupRequestToJSONTyped(value?: ConfigRuledbCreateWhatGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'and': PmgBooleanToJSON(value['and']),
        
        'info': value['info'],
        
        'invert': PmgBooleanToJSON(value['invert']),
        
        'name': value['name'],
        
    };
}

