/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigCustomscoresRevertScoreChangesResponse
 */
export interface ConfigCustomscoresRevertScoreChangesResponse {

    /**
     * 
     * @type {any}
     * @memberof ConfigCustomscoresRevertScoreChangesResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigCustomscoresRevertScoreChangesResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigCustomscoresRevertScoreChangesResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigCustomscoresRevertScoreChangesResponse interface.
 */
export function instanceOfConfigCustomscoresRevertScoreChangesResponse(value: object): value is ConfigCustomscoresRevertScoreChangesResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigCustomscoresRevertScoreChangesResponseFromJSON(json: any): ConfigCustomscoresRevertScoreChangesResponse {
    return ConfigCustomscoresRevertScoreChangesResponseFromJSONTyped(json, false);
}

export function ConfigCustomscoresRevertScoreChangesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigCustomscoresRevertScoreChangesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigCustomscoresRevertScoreChangesResponseToJSON(json: any): ConfigCustomscoresRevertScoreChangesResponse {
    return ConfigCustomscoresRevertScoreChangesResponseToJSONTyped(json, false);
}

export function ConfigCustomscoresRevertScoreChangesResponseToJSONTyped(value?: ConfigCustomscoresRevertScoreChangesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

