/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface ConfigRuledbMatchfieldRequest
 */
export interface ConfigRuledbMatchfieldRequest {

    /**
     * The Field
     * @type {string}
     * @memberof ConfigRuledbMatchfieldRequest
     */
    field: string;

    /**
     * only match the headers in the first MIME-Part
     * @type {PmgBoolean}
     * @memberof ConfigRuledbMatchfieldRequest
     */
    topPartOnly?: PmgBoolean;

    /**
     * The Value
     * @type {string}
     * @memberof ConfigRuledbMatchfieldRequest
     */
    value: string;

}



/**
 * Check if a given object implements the ConfigRuledbMatchfieldRequest interface.
 */
export function instanceOfConfigRuledbMatchfieldRequest(value: object): value is ConfigRuledbMatchfieldRequest {
    
    if (!('field' in value) || value['field'] === undefined) return false;
    
    
    if (!('value' in value) || value['value'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbMatchfieldRequestFromJSON(json: any): ConfigRuledbMatchfieldRequest {
    return ConfigRuledbMatchfieldRequestFromJSONTyped(json, false);
}

export function ConfigRuledbMatchfieldRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbMatchfieldRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'field': json['field'],
        
        'topPartOnly': json['top-part-only'] == null ? undefined : PmgBooleanFromJSON(json['top-part-only']),
        
        'value': json['value'],
        
    };
}

export function ConfigRuledbMatchfieldRequestToJSON(json: any): ConfigRuledbMatchfieldRequest {
    return ConfigRuledbMatchfieldRequestToJSONTyped(json, false);
}

export function ConfigRuledbMatchfieldRequestToJSONTyped(value?: ConfigRuledbMatchfieldRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'field': value['field'],
        
        'top-part-only': PmgBooleanToJSON(value['topPartOnly']),
        
        'value': value['value'],
        
    };
}

