/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuledbDomainRequest
 */
export interface ConfigRuledbDomainRequest {

    /**
     * DNS domain name (Sender).
     * @type {string}
     * @memberof ConfigRuledbDomainRequest
     */
    domain: string;

}

/**
 * Check if a given object implements the ConfigRuledbDomainRequest interface.
 */
export function instanceOfConfigRuledbDomainRequest(value: object): value is ConfigRuledbDomainRequest {
    
    if (!('domain' in value) || value['domain'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbDomainRequestFromJSON(json: any): ConfigRuledbDomainRequest {
    return ConfigRuledbDomainRequestFromJSONTyped(json, false);
}

export function ConfigRuledbDomainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbDomainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'domain': json['domain'],
        
    };
}

export function ConfigRuledbDomainRequestToJSON(json: any): ConfigRuledbDomainRequest {
    return ConfigRuledbDomainRequestToJSONTyped(json, false);
}

export function ConfigRuledbDomainRequestToJSONTyped(value?: ConfigRuledbDomainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'domain': value['domain'],
        
    };
}

