/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuledbReadBccResponseData
 */
export interface ConfigRuledbReadBccResponseData {

    /**
     * 
     * @type {string}
     * @memberof ConfigRuledbReadBccResponseData
     */
    id: string;

}

/**
 * Check if a given object implements the ConfigRuledbReadBccResponseData interface.
 */
export function instanceOfConfigRuledbReadBccResponseData(value: object): value is ConfigRuledbReadBccResponseData {
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbReadBccResponseDataFromJSON(json: any): ConfigRuledbReadBccResponseData {
    return ConfigRuledbReadBccResponseDataFromJSONTyped(json, false);
}

export function ConfigRuledbReadBccResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbReadBccResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'id': json['id'],
        
    };
}

export function ConfigRuledbReadBccResponseDataToJSON(json: any): ConfigRuledbReadBccResponseData {
    return ConfigRuledbReadBccResponseDataToJSONTyped(json, false);
}

export function ConfigRuledbReadBccResponseDataToJSONTyped(value?: ConfigRuledbReadBccResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'id': value['id'],
        
    };
}

