/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigDkimGetDomainsResponseDataInner } from './ConfigDkimGetDomainsResponseDataInner';
import {
    ConfigDkimGetDomainsResponseDataInnerFromJSON,
    ConfigDkimGetDomainsResponseDataInnerFromJSONTyped,
    ConfigDkimGetDomainsResponseDataInnerToJSON,
    ConfigDkimGetDomainsResponseDataInnerToJSONTyped,
} from './ConfigDkimGetDomainsResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigDomainsGetDomainsResponse
 */
export interface ConfigDomainsGetDomainsResponse {

    /**
     * 
     * @type {Array<ConfigDkimGetDomainsResponseDataInner>}
     * @memberof ConfigDomainsGetDomainsResponse
     */
    data: Array<ConfigDkimGetDomainsResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigDomainsGetDomainsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigDomainsGetDomainsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigDomainsGetDomainsResponse interface.
 */
export function instanceOfConfigDomainsGetDomainsResponse(value: object): value is ConfigDomainsGetDomainsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigDomainsGetDomainsResponseFromJSON(json: any): ConfigDomainsGetDomainsResponse {
    return ConfigDomainsGetDomainsResponseFromJSONTyped(json, false);
}

export function ConfigDomainsGetDomainsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDomainsGetDomainsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigDkimGetDomainsResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigDomainsGetDomainsResponseToJSON(json: any): ConfigDomainsGetDomainsResponse {
    return ConfigDomainsGetDomainsResponseToJSONTyped(json, false);
}

export function ConfigDomainsGetDomainsResponseToJSONTyped(value?: ConfigDomainsGetDomainsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigDkimGetDomainsResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

