/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigTransportGetTransportResponseDataInner } from './ConfigTransportGetTransportResponseDataInner';
import {
    ConfigTransportGetTransportResponseDataInnerFromJSON,
    ConfigTransportGetTransportResponseDataInnerFromJSONTyped,
    ConfigTransportGetTransportResponseDataInnerToJSON,
    ConfigTransportGetTransportResponseDataInnerToJSONTyped,
} from './ConfigTransportGetTransportResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigTransportReadGetTransportResponse
 */
export interface ConfigTransportReadGetTransportResponse {

    /**
     * 
     * @type {ConfigTransportGetTransportResponseDataInner}
     * @memberof ConfigTransportReadGetTransportResponse
     */
    data: ConfigTransportGetTransportResponseDataInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigTransportReadGetTransportResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigTransportReadGetTransportResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigTransportReadGetTransportResponse interface.
 */
export function instanceOfConfigTransportReadGetTransportResponse(value: object): value is ConfigTransportReadGetTransportResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigTransportReadGetTransportResponseFromJSON(json: any): ConfigTransportReadGetTransportResponse {
    return ConfigTransportReadGetTransportResponseFromJSONTyped(json, false);
}

export function ConfigTransportReadGetTransportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTransportReadGetTransportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigTransportGetTransportResponseDataInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigTransportReadGetTransportResponseToJSON(json: any): ConfigTransportReadGetTransportResponse {
    return ConfigTransportReadGetTransportResponseToJSONTyped(json, false);
}

export function ConfigTransportReadGetTransportResponseToJSONTyped(value?: ConfigTransportReadGetTransportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigTransportGetTransportResponseDataInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

