/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigRuledbGetConfigResponseData } from './ConfigRuledbGetConfigResponseData';
import {
    ConfigRuledbGetConfigResponseDataFromJSON,
    ConfigRuledbGetConfigResponseDataFromJSONTyped,
    ConfigRuledbGetConfigResponseDataToJSON,
    ConfigRuledbGetConfigResponseDataToJSONTyped,
} from './ConfigRuledbGetConfigResponseData';

/**
 * 
 * @export
 * @interface ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse
 */
export interface ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse {

    /**
     * 
     * @type {ConfigRuledbGetConfigResponseData}
     * @memberof ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse
     */
    data: ConfigRuledbGetConfigResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse interface.
 */
export function instanceOfConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse(value: object): value is ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponseFromJSON(json: any): ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse {
    return ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponseFromJSONTyped(json, false);
}

export function ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigRuledbGetConfigResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponseToJSON(json: any): ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse {
    return ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponseToJSONTyped(json, false);
}

export function ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponseToJSONTyped(value?: ConfigRuledbGetConfigRuledbWhoByOgroupConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigRuledbGetConfigResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

