/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface ConfigSpamUpdateSpamSectionRequest
 */
export interface ConfigSpamUpdateSpamSectionRequest {

    /**
     * Additional score for bounce mails.
     * @type {number}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    bounceScore?: number;

    /**
     * Score for ClamAV heuristics (Encrypted Archives/Documents, PhishingScanURLs, ...).
     * @type {number}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    clamavHeuristicScore?: number;

    /**
     * A list of settings you want to delete.
     * @type {string}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    _delete?: string;

    /**
     * Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    digest?: string;

    /**
     * Extract text from attachments (doc, pdf, rtf, images) and scan for spam.
     * @type {PmgBoolean}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    extractText?: PmgBoolean;

    /**
     * This option is used to specify which languages are considered OK for incoming mail.
     * @type {string}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    languages?: string;

    /**
     * Maximum size of spam messages in bytes.
     * @type {number}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    maxspamsize?: bigint | string | number;

    /**
     * Enable real time blocklists (RBL) checks.
     * @type {PmgBoolean}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    rblChecks?: PmgBoolean;

    /**
     * Use the Auto-Welcomelist plugin.
     * @type {PmgBoolean}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    useAwl?: PmgBoolean;

    /**
     * Whether to use the naive-Bayesian-style classifier.
     * @type {PmgBoolean}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    useBayes?: PmgBoolean;

    /**
     * Whether to use Razor2, if it is available.
     * @type {PmgBoolean}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    useRazor?: PmgBoolean;

    /**
     * Welcomelist legitimate bounce relays.
     * @type {string}
     * @memberof ConfigSpamUpdateSpamSectionRequest
     */
    wlBounceRelays?: string;

}



/**
 * Check if a given object implements the ConfigSpamUpdateSpamSectionRequest interface.
 */
export function instanceOfConfigSpamUpdateSpamSectionRequest(value: object): value is ConfigSpamUpdateSpamSectionRequest {
    
    
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ConfigSpamUpdateSpamSectionRequestFromJSON(json: any): ConfigSpamUpdateSpamSectionRequest {
    return ConfigSpamUpdateSpamSectionRequestFromJSONTyped(json, false);
}

export function ConfigSpamUpdateSpamSectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigSpamUpdateSpamSectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'bounceScore': json['bounce_score'] == null ? undefined : json['bounce_score'],
        
        'clamavHeuristicScore': json['clamav_heuristic_score'] == null ? undefined : json['clamav_heuristic_score'],
        
        '_delete': json['delete'] == null ? undefined : json['delete'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'extractText': json['extract_text'] == null ? undefined : PmgBooleanFromJSON(json['extract_text']),
        
        'languages': json['languages'] == null ? undefined : json['languages'],
        
        'maxspamsize': json['maxspamsize'] == null ? undefined : BigInt(json['maxspamsize']),
        
        'rblChecks': json['rbl_checks'] == null ? undefined : PmgBooleanFromJSON(json['rbl_checks']),
        
        'useAwl': json['use_awl'] == null ? undefined : PmgBooleanFromJSON(json['use_awl']),
        
        'useBayes': json['use_bayes'] == null ? undefined : PmgBooleanFromJSON(json['use_bayes']),
        
        'useRazor': json['use_razor'] == null ? undefined : PmgBooleanFromJSON(json['use_razor']),
        
        'wlBounceRelays': json['wl_bounce_relays'] == null ? undefined : json['wl_bounce_relays'],
        
    };
}

export function ConfigSpamUpdateSpamSectionRequestToJSON(json: any): ConfigSpamUpdateSpamSectionRequest {
    return ConfigSpamUpdateSpamSectionRequestToJSONTyped(json, false);
}

export function ConfigSpamUpdateSpamSectionRequestToJSONTyped(value?: ConfigSpamUpdateSpamSectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'bounce_score': value['bounceScore'],
        
        'clamav_heuristic_score': value['clamavHeuristicScore'],
        
        'delete': value['_delete'],
        
        'digest': value['digest'],
        
        'extract_text': PmgBooleanToJSON(value['extractText']),
        
        'languages': value['languages'],
        
        'maxspamsize': value['maxspamsize'] == null ? undefined : String(value['maxspamsize']),
        
        'rbl_checks': PmgBooleanToJSON(value['rblChecks']),
        
        'use_awl': PmgBooleanToJSON(value['useAwl']),
        
        'use_bayes': PmgBooleanToJSON(value['useBayes']),
        
        'use_razor': PmgBooleanToJSON(value['useRazor']),
        
        'wl_bounce_relays': value['wlBounceRelays'],
        
    };
}

