/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuledbCreateRuleResponse
 */
export interface ConfigRuledbCreateRuleResponse {

    /**
     * 
     * @type {number}
     * @memberof ConfigRuledbCreateRuleResponse
     */
    data: bigint | string | number;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbCreateRuleResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbCreateRuleResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbCreateRuleResponse interface.
 */
export function instanceOfConfigRuledbCreateRuleResponse(value: object): value is ConfigRuledbCreateRuleResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbCreateRuleResponseFromJSON(json: any): ConfigRuledbCreateRuleResponse {
    return ConfigRuledbCreateRuleResponseFromJSONTyped(json, false);
}

export function ConfigRuledbCreateRuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbCreateRuleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': BigInt(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbCreateRuleResponseToJSON(json: any): ConfigRuledbCreateRuleResponse {
    return ConfigRuledbCreateRuleResponseToJSONTyped(json, false);
}

export function ConfigRuledbCreateRuleResponseToJSONTyped(value?: ConfigRuledbCreateRuleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': String(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

