/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigDkimCreateDomainsRequest
 */
export interface ConfigDkimCreateDomainsRequest {

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigDkimCreateDomainsRequest
     */
    comment?: string;

    /**
     * Domain name.
     * @type {string}
     * @memberof ConfigDkimCreateDomainsRequest
     */
    domain: string;

}

/**
 * Check if a given object implements the ConfigDkimCreateDomainsRequest interface.
 */
export function instanceOfConfigDkimCreateDomainsRequest(value: object): value is ConfigDkimCreateDomainsRequest {
    
    
    if (!('domain' in value) || value['domain'] === undefined) return false;
    
    return true;
}

export function ConfigDkimCreateDomainsRequestFromJSON(json: any): ConfigDkimCreateDomainsRequest {
    return ConfigDkimCreateDomainsRequestFromJSONTyped(json, false);
}

export function ConfigDkimCreateDomainsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDkimCreateDomainsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'domain': json['domain'],
        
    };
}

export function ConfigDkimCreateDomainsRequestToJSON(json: any): ConfigDkimCreateDomainsRequest {
    return ConfigDkimCreateDomainsRequestToJSONTyped(json, false);
}

export function ConfigDkimCreateDomainsRequestToJSONTyped(value?: ConfigDkimCreateDomainsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'domain': value['domain'],
        
    };
}

