/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigRuledbListRulesResponseDataInner } from './ConfigRuledbListRulesResponseDataInner';
import {
    ConfigRuledbListRulesResponseDataInnerFromJSON,
    ConfigRuledbListRulesResponseDataInnerFromJSONTyped,
    ConfigRuledbListRulesResponseDataInnerToJSON,
    ConfigRuledbListRulesResponseDataInnerToJSONTyped,
} from './ConfigRuledbListRulesResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigRuledbReadLdapuserResponse
 */
export interface ConfigRuledbReadLdapuserResponse {

    /**
     * 
     * @type {ConfigRuledbListRulesResponseDataInner}
     * @memberof ConfigRuledbReadLdapuserResponse
     */
    data: ConfigRuledbListRulesResponseDataInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbReadLdapuserResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbReadLdapuserResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbReadLdapuserResponse interface.
 */
export function instanceOfConfigRuledbReadLdapuserResponse(value: object): value is ConfigRuledbReadLdapuserResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbReadLdapuserResponseFromJSON(json: any): ConfigRuledbReadLdapuserResponse {
    return ConfigRuledbReadLdapuserResponseFromJSONTyped(json, false);
}

export function ConfigRuledbReadLdapuserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbReadLdapuserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigRuledbListRulesResponseDataInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbReadLdapuserResponseToJSON(json: any): ConfigRuledbReadLdapuserResponse {
    return ConfigRuledbReadLdapuserResponseToJSONTyped(json, false);
}

export function ConfigRuledbReadLdapuserResponseToJSONTyped(value?: ConfigRuledbReadLdapuserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigRuledbListRulesResponseDataInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

