/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';
import type { PmgConfigMailProtocolEnum } from './PmgConfigMailProtocolEnum';
import {
    PmgConfigMailProtocolEnumFromJSON,
    PmgConfigMailProtocolEnumFromJSONTyped,
    PmgConfigMailProtocolEnumToJSON,
    PmgConfigMailProtocolEnumToJSONTyped,
} from './PmgConfigMailProtocolEnum';

/**
 * 
 * @export
 * @interface ConfigTransportCreateTransportRequest
 */
export interface ConfigTransportCreateTransportRequest {

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigTransportCreateTransportRequest
     */
    comment?: string;

    /**
     * Domain name.
     * @type {string}
     * @memberof ConfigTransportCreateTransportRequest
     */
    domain: string;

    /**
     * Target host (name or IP address).
     * @type {string}
     * @memberof ConfigTransportCreateTransportRequest
     */
    host: string;

    /**
     * Transport port.
     * @type {number}
     * @memberof ConfigTransportCreateTransportRequest
     */
    port?: number;

    /**
     * Transport protocol.
     * @type {PmgConfigMailProtocolEnum}
     * @memberof ConfigTransportCreateTransportRequest
     */
    protocol?: PmgConfigMailProtocolEnum;

    /**
     * Enable MX lookups (SMTP).
     * @type {PmgBoolean}
     * @memberof ConfigTransportCreateTransportRequest
     */
    useMx?: PmgBoolean;

}



/**
 * Check if a given object implements the ConfigTransportCreateTransportRequest interface.
 */
export function instanceOfConfigTransportCreateTransportRequest(value: object): value is ConfigTransportCreateTransportRequest {
    
    
    if (!('domain' in value) || value['domain'] === undefined) return false;
    
    if (!('host' in value) || value['host'] === undefined) return false;
    
    
    
    
    return true;
}

export function ConfigTransportCreateTransportRequestFromJSON(json: any): ConfigTransportCreateTransportRequest {
    return ConfigTransportCreateTransportRequestFromJSONTyped(json, false);
}

export function ConfigTransportCreateTransportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTransportCreateTransportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'domain': json['domain'],
        
        'host': json['host'],
        
        'port': json['port'] == null ? undefined : json['port'],
        
        'protocol': json['protocol'] == null ? undefined : PmgConfigMailProtocolEnumFromJSON(json['protocol']),
        
        'useMx': json['use_mx'] == null ? undefined : PmgBooleanFromJSON(json['use_mx']),
        
    };
}

export function ConfigTransportCreateTransportRequestToJSON(json: any): ConfigTransportCreateTransportRequest {
    return ConfigTransportCreateTransportRequestToJSONTyped(json, false);
}

export function ConfigTransportCreateTransportRequestToJSONTyped(value?: ConfigTransportCreateTransportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'domain': value['domain'],
        
        'host': value['host'],
        
        'port': value['port'],
        
        'protocol': PmgConfigMailProtocolEnumToJSON(value['protocol']),
        
        'use_mx': PmgBooleanToJSON(value['useMx']),
        
    };
}

