/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigAcmeGetAccountResponseData } from './ConfigAcmeGetAccountResponseData';
import {
    ConfigAcmeGetAccountResponseDataFromJSON,
    ConfigAcmeGetAccountResponseDataFromJSONTyped,
    ConfigAcmeGetAccountResponseDataToJSON,
    ConfigAcmeGetAccountResponseDataToJSONTyped,
} from './ConfigAcmeGetAccountResponseData';

/**
 * 
 * @export
 * @interface ConfigAcmeGetAccountResponse
 */
export interface ConfigAcmeGetAccountResponse {

    /**
     * 
     * @type {ConfigAcmeGetAccountResponseData}
     * @memberof ConfigAcmeGetAccountResponse
     */
    data: ConfigAcmeGetAccountResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigAcmeGetAccountResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigAcmeGetAccountResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigAcmeGetAccountResponse interface.
 */
export function instanceOfConfigAcmeGetAccountResponse(value: object): value is ConfigAcmeGetAccountResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigAcmeGetAccountResponseFromJSON(json: any): ConfigAcmeGetAccountResponse {
    return ConfigAcmeGetAccountResponseFromJSONTyped(json, false);
}

export function ConfigAcmeGetAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAcmeGetAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigAcmeGetAccountResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigAcmeGetAccountResponseToJSON(json: any): ConfigAcmeGetAccountResponse {
    return ConfigAcmeGetAccountResponseToJSONTyped(json, false);
}

export function ConfigAcmeGetAccountResponseToJSONTyped(value?: ConfigAcmeGetAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigAcmeGetAccountResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

