/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigLdapAddressListResponseDataInner } from './ConfigLdapAddressListResponseDataInner';
import {
    ConfigLdapAddressListResponseDataInnerFromJSON,
    ConfigLdapAddressListResponseDataInnerFromJSONTyped,
    ConfigLdapAddressListResponseDataInnerToJSON,
    ConfigLdapAddressListResponseDataInnerToJSONTyped,
} from './ConfigLdapAddressListResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigLdapAddressListResponse
 */
export interface ConfigLdapAddressListResponse {

    /**
     * 
     * @type {Array<ConfigLdapAddressListResponseDataInner>}
     * @memberof ConfigLdapAddressListResponse
     */
    data: Array<ConfigLdapAddressListResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigLdapAddressListResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigLdapAddressListResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigLdapAddressListResponse interface.
 */
export function instanceOfConfigLdapAddressListResponse(value: object): value is ConfigLdapAddressListResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigLdapAddressListResponseFromJSON(json: any): ConfigLdapAddressListResponse {
    return ConfigLdapAddressListResponseFromJSONTyped(json, false);
}

export function ConfigLdapAddressListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigLdapAddressListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigLdapAddressListResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigLdapAddressListResponseToJSON(json: any): ConfigLdapAddressListResponse {
    return ConfigLdapAddressListResponseToJSONTyped(json, false);
}

export function ConfigLdapAddressListResponseToJSONTyped(value?: ConfigLdapAddressListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigLdapAddressListResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

