/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface ConfigRuledbConfigResponseData
 */
export interface ConfigRuledbConfigResponseData {

    /**
     * 
     * @type {PmgBoolean}
     * @memberof ConfigRuledbConfigResponseData
     */
    active: PmgBoolean;

    /**
     * 
     * @type {number}
     * @memberof ConfigRuledbConfigResponseData
     */
    direction: bigint | string | number;

    /**
     * 
     * @type {number}
     * @memberof ConfigRuledbConfigResponseData
     */
    id: bigint | string | number;

    /**
     * 
     * @type {string}
     * @memberof ConfigRuledbConfigResponseData
     */
    name: string;

    /**
     * 
     * @type {number}
     * @memberof ConfigRuledbConfigResponseData
     */
    priority: bigint | string | number;

}



/**
 * Check if a given object implements the ConfigRuledbConfigResponseData interface.
 */
export function instanceOfConfigRuledbConfigResponseData(value: object): value is ConfigRuledbConfigResponseData {
    
    if (!('active' in value) || value['active'] === undefined) return false;
    
    if (!('direction' in value) || value['direction'] === undefined) return false;
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    if (!('priority' in value) || value['priority'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbConfigResponseDataFromJSON(json: any): ConfigRuledbConfigResponseData {
    return ConfigRuledbConfigResponseDataFromJSONTyped(json, false);
}

export function ConfigRuledbConfigResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbConfigResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'active': PmgBooleanFromJSON(json['active']),
        
        'direction': BigInt(json['direction']),
        
        'id': BigInt(json['id']),
        
        'name': json['name'],
        
        'priority': BigInt(json['priority']),
        
    };
}

export function ConfigRuledbConfigResponseDataToJSON(json: any): ConfigRuledbConfigResponseData {
    return ConfigRuledbConfigResponseDataToJSONTyped(json, false);
}

export function ConfigRuledbConfigResponseDataToJSONTyped(value?: ConfigRuledbConfigResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'active': PmgBooleanToJSON(value['active']),
        
        'direction': String(value['direction']),
        
        'id': String(value['id']),
        
        'name': value['name'],
        
        'priority': String(value['priority']),
        
    };
}

