/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigRuledbListRulesResponseDataInner } from './ConfigRuledbListRulesResponseDataInner';
import {
    ConfigRuledbListRulesResponseDataInnerFromJSON,
    ConfigRuledbListRulesResponseDataInnerFromJSONTyped,
    ConfigRuledbListRulesResponseDataInnerToJSON,
    ConfigRuledbListRulesResponseDataInnerToJSONTyped,
} from './ConfigRuledbListRulesResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigWelcomelistObjectsResponse
 */
export interface ConfigWelcomelistObjectsResponse {

    /**
     * 
     * @type {Array<ConfigRuledbListRulesResponseDataInner>}
     * @memberof ConfigWelcomelistObjectsResponse
     */
    data: Array<ConfigRuledbListRulesResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigWelcomelistObjectsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigWelcomelistObjectsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigWelcomelistObjectsResponse interface.
 */
export function instanceOfConfigWelcomelistObjectsResponse(value: object): value is ConfigWelcomelistObjectsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigWelcomelistObjectsResponseFromJSON(json: any): ConfigWelcomelistObjectsResponse {
    return ConfigWelcomelistObjectsResponseFromJSONTyped(json, false);
}

export function ConfigWelcomelistObjectsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigWelcomelistObjectsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigRuledbListRulesResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigWelcomelistObjectsResponseToJSON(json: any): ConfigWelcomelistObjectsResponse {
    return ConfigWelcomelistObjectsResponseToJSONTyped(json, false);
}

export function ConfigWelcomelistObjectsResponseToJSONTyped(value?: ConfigWelcomelistObjectsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigRuledbListRulesResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

