/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigTlspolicyGetTlspolicyResponseDataInner
 */
export interface ConfigTlspolicyGetTlspolicyResponseDataInner {

    /**
     * 
     * @type {string}
     * @memberof ConfigTlspolicyGetTlspolicyResponseDataInner
     */
    destination: string;

    /**
     * 
     * @type {string}
     * @memberof ConfigTlspolicyGetTlspolicyResponseDataInner
     */
    policy: string;

}

/**
 * Check if a given object implements the ConfigTlspolicyGetTlspolicyResponseDataInner interface.
 */
export function instanceOfConfigTlspolicyGetTlspolicyResponseDataInner(value: object): value is ConfigTlspolicyGetTlspolicyResponseDataInner {
    
    if (!('destination' in value) || value['destination'] === undefined) return false;
    
    if (!('policy' in value) || value['policy'] === undefined) return false;
    
    return true;
}

export function ConfigTlspolicyGetTlspolicyResponseDataInnerFromJSON(json: any): ConfigTlspolicyGetTlspolicyResponseDataInner {
    return ConfigTlspolicyGetTlspolicyResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigTlspolicyGetTlspolicyResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTlspolicyGetTlspolicyResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'destination': json['destination'],
        
        'policy': json['policy'],
        
    };
}

export function ConfigTlspolicyGetTlspolicyResponseDataInnerToJSON(json: any): ConfigTlspolicyGetTlspolicyResponseDataInner {
    return ConfigTlspolicyGetTlspolicyResponseDataInnerToJSONTyped(json, false);
}

export function ConfigTlspolicyGetTlspolicyResponseDataInnerToJSONTyped(value?: ConfigTlspolicyGetTlspolicyResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'destination': value['destination'],
        
        'policy': value['policy'],
        
    };
}

