/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigMynetworksGetMynetworksResponseDataInner
 */
export interface ConfigMynetworksGetMynetworksResponseDataInner {

    /**
     * 
     * @type {string}
     * @memberof ConfigMynetworksGetMynetworksResponseDataInner
     */
    cidr: string;

}

/**
 * Check if a given object implements the ConfigMynetworksGetMynetworksResponseDataInner interface.
 */
export function instanceOfConfigMynetworksGetMynetworksResponseDataInner(value: object): value is ConfigMynetworksGetMynetworksResponseDataInner {
    
    if (!('cidr' in value) || value['cidr'] === undefined) return false;
    
    return true;
}

export function ConfigMynetworksGetMynetworksResponseDataInnerFromJSON(json: any): ConfigMynetworksGetMynetworksResponseDataInner {
    return ConfigMynetworksGetMynetworksResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigMynetworksGetMynetworksResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigMynetworksGetMynetworksResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'cidr': json['cidr'],
        
    };
}

export function ConfigMynetworksGetMynetworksResponseDataInnerToJSON(json: any): ConfigMynetworksGetMynetworksResponseDataInner {
    return ConfigMynetworksGetMynetworksResponseDataInnerToJSONTyped(json, false);
}

export function ConfigMynetworksGetMynetworksResponseDataInnerToJSONTyped(value?: ConfigMynetworksGetMynetworksResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'cidr': value['cidr'],
        
    };
}

