/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgNotifyEnum } from './PmgNotifyEnum';
import {
    PmgNotifyEnumFromJSON,
    PmgNotifyEnumFromJSONTyped,
    PmgNotifyEnumToJSON,
    PmgNotifyEnumToJSONTyped,
} from './PmgNotifyEnum';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface ConfigPbsCreatePbsRequest
 */
export interface ConfigPbsCreatePbsRequest {

    /**
     * Proxmox Backup Server datastore name.
     * @type {string}
     * @memberof ConfigPbsCreatePbsRequest
     */
    datastore: string;

    /**
     * Flag to disable (deactivate) the entry.
     * @type {PmgBoolean}
     * @memberof ConfigPbsCreatePbsRequest
     */
    disable?: PmgBoolean;

    /**
     * Certificate SHA 256 fingerprint.
     * @type {string}
     * @memberof ConfigPbsCreatePbsRequest
     */
    fingerprint?: string;

    /**
     * Include statistics in scheduled backups
     * @type {PmgBoolean}
     * @memberof ConfigPbsCreatePbsRequest
     */
    includeStatistics?: PmgBoolean;

    /**
     * Keep backups for the last <N> different days. If there is more than one backup for a single day, only the latest one is kept.
     * @type {number}
     * @memberof ConfigPbsCreatePbsRequest
     */
    keepDaily?: bigint | string | number;

    /**
     * Keep backups for the last <N> different hours. If there is more than one backup for a single hour, only the latest one is kept.
     * @type {number}
     * @memberof ConfigPbsCreatePbsRequest
     */
    keepHourly?: bigint | string | number;

    /**
     * Keep the last <N> backups.
     * @type {number}
     * @memberof ConfigPbsCreatePbsRequest
     */
    keepLast?: bigint | string | number;

    /**
     * Keep backups for the last <N> different months. If there is more than one backup for a single month, only the latest one is kept.
     * @type {number}
     * @memberof ConfigPbsCreatePbsRequest
     */
    keepMonthly?: bigint | string | number;

    /**
     * Keep backups for the last <N> different weeks. If there ismore than one backup for a single week, only the latest one is kept.
     * @type {number}
     * @memberof ConfigPbsCreatePbsRequest
     */
    keepWeekly?: bigint | string | number;

    /**
     * Keep backups for the last <N> different years. If there is more than one backup for a single year, only the latest one is kept.
     * @type {number}
     * @memberof ConfigPbsCreatePbsRequest
     */
    keepYearly?: bigint | string | number;

    /**
     * Proxmox Backup Server namespace in the datastore, defaults to the root NS.
     * @type {string}
     * @memberof ConfigPbsCreatePbsRequest
     */
    namespace?: string;

    /**
     * Specify when to notify via e-mail
     * @type {PmgNotifyEnum}
     * @memberof ConfigPbsCreatePbsRequest
     */
    notify?: PmgNotifyEnum;

    /**
     * Password or API token secret for the user on the Proxmox Backup Server.
     * @type {string}
     * @memberof ConfigPbsCreatePbsRequest
     */
    password?: string;

    /**
     * Non-default port for Proxmox Backup Server.
     * @type {number}
     * @memberof ConfigPbsCreatePbsRequest
     */
    port?: number;

    /**
     * Proxmox Backup Server ID.
     * @type {string}
     * @memberof ConfigPbsCreatePbsRequest
     */
    remote: string;

    /**
     * Proxmox Backup Server address.
     * @type {string}
     * @memberof ConfigPbsCreatePbsRequest
     */
    server: string;

    /**
     * Username or API token ID on the Proxmox Backup Server
     * @type {string}
     * @memberof ConfigPbsCreatePbsRequest
     */
    username?: string;

}



/**
 * Check if a given object implements the ConfigPbsCreatePbsRequest interface.
 */
export function instanceOfConfigPbsCreatePbsRequest(value: object): value is ConfigPbsCreatePbsRequest {
    
    if (!('datastore' in value) || value['datastore'] === undefined) return false;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    if (!('remote' in value) || value['remote'] === undefined) return false;
    
    if (!('server' in value) || value['server'] === undefined) return false;
    
    
    return true;
}

export function ConfigPbsCreatePbsRequestFromJSON(json: any): ConfigPbsCreatePbsRequest {
    return ConfigPbsCreatePbsRequestFromJSONTyped(json, false);
}

export function ConfigPbsCreatePbsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigPbsCreatePbsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'datastore': json['datastore'],
        
        'disable': json['disable'] == null ? undefined : PmgBooleanFromJSON(json['disable']),
        
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        
        'includeStatistics': json['include-statistics'] == null ? undefined : PmgBooleanFromJSON(json['include-statistics']),
        
        'keepDaily': json['keep-daily'] == null ? undefined : BigInt(json['keep-daily']),
        
        'keepHourly': json['keep-hourly'] == null ? undefined : BigInt(json['keep-hourly']),
        
        'keepLast': json['keep-last'] == null ? undefined : BigInt(json['keep-last']),
        
        'keepMonthly': json['keep-monthly'] == null ? undefined : BigInt(json['keep-monthly']),
        
        'keepWeekly': json['keep-weekly'] == null ? undefined : BigInt(json['keep-weekly']),
        
        'keepYearly': json['keep-yearly'] == null ? undefined : BigInt(json['keep-yearly']),
        
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        
        'notify': json['notify'] == null ? undefined : PmgNotifyEnumFromJSON(json['notify']),
        
        'password': json['password'] == null ? undefined : json['password'],
        
        'port': json['port'] == null ? undefined : json['port'],
        
        'remote': json['remote'],
        
        'server': json['server'],
        
        'username': json['username'] == null ? undefined : json['username'],
        
    };
}

export function ConfigPbsCreatePbsRequestToJSON(json: any): ConfigPbsCreatePbsRequest {
    return ConfigPbsCreatePbsRequestToJSONTyped(json, false);
}

export function ConfigPbsCreatePbsRequestToJSONTyped(value?: ConfigPbsCreatePbsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'datastore': value['datastore'],
        
        'disable': PmgBooleanToJSON(value['disable']),
        
        'fingerprint': value['fingerprint'],
        
        'include-statistics': PmgBooleanToJSON(value['includeStatistics']),
        
        'keep-daily': value['keepDaily'] == null ? undefined : String(value['keepDaily']),
        
        'keep-hourly': value['keepHourly'] == null ? undefined : String(value['keepHourly']),
        
        'keep-last': value['keepLast'] == null ? undefined : String(value['keepLast']),
        
        'keep-monthly': value['keepMonthly'] == null ? undefined : String(value['keepMonthly']),
        
        'keep-weekly': value['keepWeekly'] == null ? undefined : String(value['keepWeekly']),
        
        'keep-yearly': value['keepYearly'] == null ? undefined : String(value['keepYearly']),
        
        'namespace': value['namespace'],
        
        'notify': PmgNotifyEnumToJSON(value['notify']),
        
        'password': value['password'],
        
        'port': value['port'],
        
        'remote': value['remote'],
        
        'server': value['server'],
        
        'username': value['username'],
        
    };
}

