/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigGetConfigResponseDataInner } from './ConfigGetConfigResponseDataInner';
import {
    ConfigGetConfigResponseDataInnerFromJSON,
    ConfigGetConfigResponseDataInnerFromJSONTyped,
    ConfigGetConfigResponseDataInnerToJSON,
    ConfigGetConfigResponseDataInnerToJSONTyped,
} from './ConfigGetConfigResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigGetConfigResponse
 */
export interface ConfigGetConfigResponse {

    /**
     * 
     * @type {Array<ConfigGetConfigResponseDataInner>}
     * @memberof ConfigGetConfigResponse
     */
    data: Array<ConfigGetConfigResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigGetConfigResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigGetConfigResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigGetConfigResponse interface.
 */
export function instanceOfConfigGetConfigResponse(value: object): value is ConfigGetConfigResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigGetConfigResponseFromJSON(json: any): ConfigGetConfigResponse {
    return ConfigGetConfigResponseFromJSONTyped(json, false);
}

export function ConfigGetConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigGetConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigGetConfigResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigGetConfigResponseToJSON(json: any): ConfigGetConfigResponse {
    return ConfigGetConfigResponseToJSONTyped(json, false);
}

export function ConfigGetConfigResponseToJSONTyped(value?: ConfigGetConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigGetConfigResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

