/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigDkimGetDomainsResponseDataInner } from './ConfigDkimGetDomainsResponseDataInner';
import {
    ConfigDkimGetDomainsResponseDataInnerFromJSON,
    ConfigDkimGetDomainsResponseDataInnerFromJSONTyped,
    ConfigDkimGetDomainsResponseDataInnerToJSON,
    ConfigDkimGetDomainsResponseDataInnerToJSONTyped,
} from './ConfigDkimGetDomainsResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigDkimReadGetDomainsResponse
 */
export interface ConfigDkimReadGetDomainsResponse {

    /**
     * 
     * @type {ConfigDkimGetDomainsResponseDataInner}
     * @memberof ConfigDkimReadGetDomainsResponse
     */
    data: ConfigDkimGetDomainsResponseDataInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigDkimReadGetDomainsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigDkimReadGetDomainsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigDkimReadGetDomainsResponse interface.
 */
export function instanceOfConfigDkimReadGetDomainsResponse(value: object): value is ConfigDkimReadGetDomainsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigDkimReadGetDomainsResponseFromJSON(json: any): ConfigDkimReadGetDomainsResponse {
    return ConfigDkimReadGetDomainsResponseFromJSONTyped(json, false);
}

export function ConfigDkimReadGetDomainsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDkimReadGetDomainsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigDkimGetDomainsResponseDataInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigDkimReadGetDomainsResponseToJSON(json: any): ConfigDkimReadGetDomainsResponse {
    return ConfigDkimReadGetDomainsResponseToJSONTyped(json, false);
}

export function ConfigDkimReadGetDomainsResponseToJSONTyped(value?: ConfigDkimReadGetDomainsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigDkimGetDomainsResponseDataInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

