/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';
import type { PmgConfigMailProtocolEnum } from './PmgConfigMailProtocolEnum';
import {
    PmgConfigMailProtocolEnumFromJSON,
    PmgConfigMailProtocolEnumFromJSONTyped,
    PmgConfigMailProtocolEnumToJSON,
    PmgConfigMailProtocolEnumToJSONTyped,
} from './PmgConfigMailProtocolEnum';

/**
 * 
 * @export
 * @interface ConfigTransportWriteRequest
 */
export interface ConfigTransportWriteRequest {

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigTransportWriteRequest
     */
    comment?: string;

    /**
     * Target host (name or IP address).
     * @type {string}
     * @memberof ConfigTransportWriteRequest
     */
    host?: string;

    /**
     * Transport port.
     * @type {number}
     * @memberof ConfigTransportWriteRequest
     */
    port?: number;

    /**
     * Transport protocol.
     * @type {PmgConfigMailProtocolEnum}
     * @memberof ConfigTransportWriteRequest
     */
    protocol?: PmgConfigMailProtocolEnum;

    /**
     * Enable MX lookups (SMTP).
     * @type {PmgBoolean}
     * @memberof ConfigTransportWriteRequest
     */
    useMx?: PmgBoolean;

}



/**
 * Check if a given object implements the ConfigTransportWriteRequest interface.
 */
export function instanceOfConfigTransportWriteRequest(value: object): value is ConfigTransportWriteRequest {
    
    
    
    
    
    
    return true;
}

export function ConfigTransportWriteRequestFromJSON(json: any): ConfigTransportWriteRequest {
    return ConfigTransportWriteRequestFromJSONTyped(json, false);
}

export function ConfigTransportWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTransportWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'host': json['host'] == null ? undefined : json['host'],
        
        'port': json['port'] == null ? undefined : json['port'],
        
        'protocol': json['protocol'] == null ? undefined : PmgConfigMailProtocolEnumFromJSON(json['protocol']),
        
        'useMx': json['use_mx'] == null ? undefined : PmgBooleanFromJSON(json['use_mx']),
        
    };
}

export function ConfigTransportWriteRequestToJSON(json: any): ConfigTransportWriteRequest {
    return ConfigTransportWriteRequestToJSONTyped(json, false);
}

export function ConfigTransportWriteRequestToJSONTyped(value?: ConfigTransportWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'host': value['host'],
        
        'port': value['port'],
        
        'protocol': PmgConfigMailProtocolEnumToJSON(value['protocol']),
        
        'use_mx': PmgBooleanToJSON(value['useMx']),
        
    };
}

