/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigDkimGetSelectorListResponseDataInner
 */
export interface ConfigDkimGetSelectorListResponseDataInner {

    /**
     * 
     * @type {string}
     * @memberof ConfigDkimGetSelectorListResponseDataInner
     */
    selector: string;

}

/**
 * Check if a given object implements the ConfigDkimGetSelectorListResponseDataInner interface.
 */
export function instanceOfConfigDkimGetSelectorListResponseDataInner(value: object): value is ConfigDkimGetSelectorListResponseDataInner {
    
    if (!('selector' in value) || value['selector'] === undefined) return false;
    
    return true;
}

export function ConfigDkimGetSelectorListResponseDataInnerFromJSON(json: any): ConfigDkimGetSelectorListResponseDataInner {
    return ConfigDkimGetSelectorListResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigDkimGetSelectorListResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDkimGetSelectorListResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'selector': json['selector'],
        
    };
}

export function ConfigDkimGetSelectorListResponseDataInnerToJSON(json: any): ConfigDkimGetSelectorListResponseDataInner {
    return ConfigDkimGetSelectorListResponseDataInnerToJSONTyped(json, false);
}

export function ConfigDkimGetSelectorListResponseDataInnerToJSONTyped(value?: ConfigDkimGetSelectorListResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'selector': value['selector'],
        
    };
}

