/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigCustomscoresEditScoreRequest
 */
export interface ConfigCustomscoresEditScoreRequest {

    /**
     * The Comment.
     * @type {string}
     * @memberof ConfigCustomscoresEditScoreRequest
     */
    comment?: string;

    /**
     * Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ConfigCustomscoresEditScoreRequest
     */
    digest?: string;

    /**
     * The score the rule should be valued at.
     * @type {number}
     * @memberof ConfigCustomscoresEditScoreRequest
     */
    score: number;

}

/**
 * Check if a given object implements the ConfigCustomscoresEditScoreRequest interface.
 */
export function instanceOfConfigCustomscoresEditScoreRequest(value: object): value is ConfigCustomscoresEditScoreRequest {
    
    
    
    if (!('score' in value) || value['score'] === undefined) return false;
    
    return true;
}

export function ConfigCustomscoresEditScoreRequestFromJSON(json: any): ConfigCustomscoresEditScoreRequest {
    return ConfigCustomscoresEditScoreRequestFromJSONTyped(json, false);
}

export function ConfigCustomscoresEditScoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigCustomscoresEditScoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'score': json['score'],
        
    };
}

export function ConfigCustomscoresEditScoreRequestToJSON(json: any): ConfigCustomscoresEditScoreRequest {
    return ConfigCustomscoresEditScoreRequestToJSONTyped(json, false);
}

export function ConfigCustomscoresEditScoreRequestToJSONTyped(value?: ConfigCustomscoresEditScoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'digest': value['digest'],
        
        'score': value['score'],
        
    };
}

