/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessGetAccessResponseDataInner } from './AccessGetAccessResponseDataInner';
import {
    AccessGetAccessResponseDataInnerFromJSON,
    AccessGetAccessResponseDataInnerFromJSONTyped,
    AccessGetAccessResponseDataInnerToJSON,
    AccessGetAccessResponseDataInnerToJSONTyped,
} from './AccessGetAccessResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigRuledbGetRulesResponse
 */
export interface ConfigRuledbGetRulesResponse {

    /**
     * 
     * @type {Array<AccessGetAccessResponseDataInner>}
     * @memberof ConfigRuledbGetRulesResponse
     */
    data: Array<AccessGetAccessResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbGetRulesResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbGetRulesResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbGetRulesResponse interface.
 */
export function instanceOfConfigRuledbGetRulesResponse(value: object): value is ConfigRuledbGetRulesResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbGetRulesResponseFromJSON(json: any): ConfigRuledbGetRulesResponse {
    return ConfigRuledbGetRulesResponseFromJSONTyped(json, false);
}

export function ConfigRuledbGetRulesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbGetRulesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(AccessGetAccessResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbGetRulesResponseToJSON(json: any): ConfigRuledbGetRulesResponse {
    return ConfigRuledbGetRulesResponseToJSONTyped(json, false);
}

export function ConfigRuledbGetRulesResponseToJSONTyped(value?: ConfigRuledbGetRulesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(AccessGetAccessResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

