/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigRuledbReadBccResponseData } from './ConfigRuledbReadBccResponseData';
import {
    ConfigRuledbReadBccResponseDataFromJSON,
    ConfigRuledbReadBccResponseDataFromJSONTyped,
    ConfigRuledbReadBccResponseDataToJSON,
    ConfigRuledbReadBccResponseDataToJSONTyped,
} from './ConfigRuledbReadBccResponseData';

/**
 * 
 * @export
 * @interface ConfigRuledbReadNotificationResponse
 */
export interface ConfigRuledbReadNotificationResponse {

    /**
     * 
     * @type {ConfigRuledbReadBccResponseData}
     * @memberof ConfigRuledbReadNotificationResponse
     */
    data: ConfigRuledbReadBccResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbReadNotificationResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbReadNotificationResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbReadNotificationResponse interface.
 */
export function instanceOfConfigRuledbReadNotificationResponse(value: object): value is ConfigRuledbReadNotificationResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbReadNotificationResponseFromJSON(json: any): ConfigRuledbReadNotificationResponse {
    return ConfigRuledbReadNotificationResponseFromJSONTyped(json, false);
}

export function ConfigRuledbReadNotificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbReadNotificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigRuledbReadBccResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbReadNotificationResponseToJSON(json: any): ConfigRuledbReadNotificationResponse {
    return ConfigRuledbReadNotificationResponseToJSONTyped(json, false);
}

export function ConfigRuledbReadNotificationResponseToJSONTyped(value?: ConfigRuledbReadNotificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigRuledbReadBccResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

