/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigCustomscoresListScoresResponseDataInner } from './ConfigCustomscoresListScoresResponseDataInner';
import {
    ConfigCustomscoresListScoresResponseDataInnerFromJSON,
    ConfigCustomscoresListScoresResponseDataInnerFromJSONTyped,
    ConfigCustomscoresListScoresResponseDataInnerToJSON,
    ConfigCustomscoresListScoresResponseDataInnerToJSONTyped,
} from './ConfigCustomscoresListScoresResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigCustomscoresListScoresResponse
 */
export interface ConfigCustomscoresListScoresResponse {

    /**
     * 
     * @type {Array<ConfigCustomscoresListScoresResponseDataInner>}
     * @memberof ConfigCustomscoresListScoresResponse
     */
    data: Array<ConfigCustomscoresListScoresResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigCustomscoresListScoresResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigCustomscoresListScoresResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigCustomscoresListScoresResponse interface.
 */
export function instanceOfConfigCustomscoresListScoresResponse(value: object): value is ConfigCustomscoresListScoresResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigCustomscoresListScoresResponseFromJSON(json: any): ConfigCustomscoresListScoresResponse {
    return ConfigCustomscoresListScoresResponseFromJSONTyped(json, false);
}

export function ConfigCustomscoresListScoresResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigCustomscoresListScoresResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigCustomscoresListScoresResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigCustomscoresListScoresResponseToJSON(json: any): ConfigCustomscoresListScoresResponse {
    return ConfigCustomscoresListScoresResponseToJSONTyped(json, false);
}

export function ConfigCustomscoresListScoresResponseToJSONTyped(value?: ConfigCustomscoresListScoresResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigCustomscoresListScoresResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

