/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuledbNetworkRequest
 */
export interface ConfigRuledbNetworkRequest {

    /**
     * Network address in CIDR notation.
     * @type {string}
     * @memberof ConfigRuledbNetworkRequest
     */
    cidr: string;

}

/**
 * Check if a given object implements the ConfigRuledbNetworkRequest interface.
 */
export function instanceOfConfigRuledbNetworkRequest(value: object): value is ConfigRuledbNetworkRequest {
    
    if (!('cidr' in value) || value['cidr'] === undefined) return false;
    
    return true;
}

export function ConfigRuledbNetworkRequestFromJSON(json: any): ConfigRuledbNetworkRequest {
    return ConfigRuledbNetworkRequestFromJSONTyped(json, false);
}

export function ConfigRuledbNetworkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbNetworkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'cidr': json['cidr'],
        
    };
}

export function ConfigRuledbNetworkRequestToJSON(json: any): ConfigRuledbNetworkRequest {
    return ConfigRuledbNetworkRequestToJSONTyped(json, false);
}

export function ConfigRuledbNetworkRequestToJSONTyped(value?: ConfigRuledbNetworkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'cidr': value['cidr'],
        
    };
}

