/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse
 */
export interface ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse {

    /**
     * 
     * @type {any}
     * @memberof ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse interface.
 */
export function instanceOfConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse(value: object): value is ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponseFromJSON(json: any): ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse {
    return ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponseFromJSONTyped(json, false);
}

export function ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponseToJSON(json: any): ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse {
    return ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponseToJSONTyped(json, false);
}

export function ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponseToJSONTyped(value?: ConfigRuledbUpdateConfigRuledbWhoByOgroupConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

