/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigAcmeChallengeSchemaResponseDataInner
 */
export interface ConfigAcmeChallengeSchemaResponseDataInner {

    /**
     * 
     * @type {string}
     * @memberof ConfigAcmeChallengeSchemaResponseDataInner
     */
    id: string;

    /**
     * Human readable name, falls back to id
     * @type {string}
     * @memberof ConfigAcmeChallengeSchemaResponseDataInner
     */
    name: string;

    /**
     * 
     * @type {object}
     * @memberof ConfigAcmeChallengeSchemaResponseDataInner
     */
    schema: object;

    /**
     * 
     * @type {string}
     * @memberof ConfigAcmeChallengeSchemaResponseDataInner
     */
    type: string;

}

/**
 * Check if a given object implements the ConfigAcmeChallengeSchemaResponseDataInner interface.
 */
export function instanceOfConfigAcmeChallengeSchemaResponseDataInner(value: object): value is ConfigAcmeChallengeSchemaResponseDataInner {
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    if (!('schema' in value) || value['schema'] === undefined) return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    return true;
}

export function ConfigAcmeChallengeSchemaResponseDataInnerFromJSON(json: any): ConfigAcmeChallengeSchemaResponseDataInner {
    return ConfigAcmeChallengeSchemaResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigAcmeChallengeSchemaResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAcmeChallengeSchemaResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'id': json['id'],
        
        'name': json['name'],
        
        'schema': json['schema'],
        
        'type': json['type'],
        
    };
}

export function ConfigAcmeChallengeSchemaResponseDataInnerToJSON(json: any): ConfigAcmeChallengeSchemaResponseDataInner {
    return ConfigAcmeChallengeSchemaResponseDataInnerToJSONTyped(json, false);
}

export function ConfigAcmeChallengeSchemaResponseDataInnerToJSONTyped(value?: ConfigAcmeChallengeSchemaResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'id': value['id'],
        
        'name': value['name'],
        
        'schema': value['schema'],
        
        'type': value['type'],
        
    };
}

