/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigDkimWriteRequest
 */
export interface ConfigDkimWriteRequest {

    /**
     * Comment.
     * @type {string}
     * @memberof ConfigDkimWriteRequest
     */
    comment: string;

}

/**
 * Check if a given object implements the ConfigDkimWriteRequest interface.
 */
export function instanceOfConfigDkimWriteRequest(value: object): value is ConfigDkimWriteRequest {
    
    if (!('comment' in value) || value['comment'] === undefined) return false;
    
    return true;
}

export function ConfigDkimWriteRequestFromJSON(json: any): ConfigDkimWriteRequest {
    return ConfigDkimWriteRequestFromJSONTyped(json, false);
}

export function ConfigDkimWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDkimWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'],
        
    };
}

export function ConfigDkimWriteRequestToJSON(json: any): ConfigDkimWriteRequest {
    return ConfigDkimWriteRequestToJSONTyped(json, false);
}

export function ConfigDkimWriteRequestToJSONTyped(value?: ConfigDkimWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
    };
}

