/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigTlspolicyGetTlspolicyResponseDataInner } from './ConfigTlspolicyGetTlspolicyResponseDataInner';
import {
    ConfigTlspolicyGetTlspolicyResponseDataInnerFromJSON,
    ConfigTlspolicyGetTlspolicyResponseDataInnerFromJSONTyped,
    ConfigTlspolicyGetTlspolicyResponseDataInnerToJSON,
    ConfigTlspolicyGetTlspolicyResponseDataInnerToJSONTyped,
} from './ConfigTlspolicyGetTlspolicyResponseDataInner';

/**
 * 
 * @export
 * @interface ConfigTlspolicyReadGetTlspolicyResponse
 */
export interface ConfigTlspolicyReadGetTlspolicyResponse {

    /**
     * 
     * @type {ConfigTlspolicyGetTlspolicyResponseDataInner}
     * @memberof ConfigTlspolicyReadGetTlspolicyResponse
     */
    data: ConfigTlspolicyGetTlspolicyResponseDataInner;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigTlspolicyReadGetTlspolicyResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigTlspolicyReadGetTlspolicyResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigTlspolicyReadGetTlspolicyResponse interface.
 */
export function instanceOfConfigTlspolicyReadGetTlspolicyResponse(value: object): value is ConfigTlspolicyReadGetTlspolicyResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigTlspolicyReadGetTlspolicyResponseFromJSON(json: any): ConfigTlspolicyReadGetTlspolicyResponse {
    return ConfigTlspolicyReadGetTlspolicyResponseFromJSONTyped(json, false);
}

export function ConfigTlspolicyReadGetTlspolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTlspolicyReadGetTlspolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ConfigTlspolicyGetTlspolicyResponseDataInnerFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigTlspolicyReadGetTlspolicyResponseToJSON(json: any): ConfigTlspolicyReadGetTlspolicyResponse {
    return ConfigTlspolicyReadGetTlspolicyResponseToJSONTyped(json, false);
}

export function ConfigTlspolicyReadGetTlspolicyResponseToJSONTyped(value?: ConfigTlspolicyReadGetTlspolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ConfigTlspolicyGetTlspolicyResponseDataInnerToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

