/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuledbMatchfieldResponse
 */
export interface ConfigRuledbMatchfieldResponse {

    /**
     * 
     * @type {number}
     * @memberof ConfigRuledbMatchfieldResponse
     */
    data: number;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ConfigRuledbMatchfieldResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ConfigRuledbMatchfieldResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ConfigRuledbMatchfieldResponse interface.
 */
export function instanceOfConfigRuledbMatchfieldResponse(value: object): value is ConfigRuledbMatchfieldResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ConfigRuledbMatchfieldResponseFromJSON(json: any): ConfigRuledbMatchfieldResponse {
    return ConfigRuledbMatchfieldResponseFromJSONTyped(json, false);
}

export function ConfigRuledbMatchfieldResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuledbMatchfieldResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ConfigRuledbMatchfieldResponseToJSON(json: any): ConfigRuledbMatchfieldResponse {
    return ConfigRuledbMatchfieldResponseToJSONTyped(json, false);
}

export function ConfigRuledbMatchfieldResponseToJSONTyped(value?: ConfigRuledbMatchfieldResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

