/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigDkimGetDomainsResponseDataInner
 */
export interface ConfigDkimGetDomainsResponseDataInner {

    /**
     * 
     * @type {string}
     * @memberof ConfigDkimGetDomainsResponseDataInner
     */
    comment: string;

    /**
     * 
     * @type {string}
     * @memberof ConfigDkimGetDomainsResponseDataInner
     */
    domain: string;

}

/**
 * Check if a given object implements the ConfigDkimGetDomainsResponseDataInner interface.
 */
export function instanceOfConfigDkimGetDomainsResponseDataInner(value: object): value is ConfigDkimGetDomainsResponseDataInner {
    
    if (!('comment' in value) || value['comment'] === undefined) return false;
    
    if (!('domain' in value) || value['domain'] === undefined) return false;
    
    return true;
}

export function ConfigDkimGetDomainsResponseDataInnerFromJSON(json: any): ConfigDkimGetDomainsResponseDataInner {
    return ConfigDkimGetDomainsResponseDataInnerFromJSONTyped(json, false);
}

export function ConfigDkimGetDomainsResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDkimGetDomainsResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'],
        
        'domain': json['domain'],
        
    };
}

export function ConfigDkimGetDomainsResponseDataInnerToJSON(json: any): ConfigDkimGetDomainsResponseDataInner {
    return ConfigDkimGetDomainsResponseDataInnerToJSONTyped(json, false);
}

export function ConfigDkimGetDomainsResponseDataInnerToJSONTyped(value?: ConfigDkimGetDomainsResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'domain': value['domain'],
        
    };
}

