/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesClamavGetClamavResponseDataInner
 */
export interface NodesClamavGetClamavResponseDataInner {

    /**
     * URL slug of the child resource (inferred from PVE HATEOAS link).
     * @type {string}
     * @memberof NodesClamavGetClamavResponseDataInner
     */
    subdir: string;

}

/**
 * Check if a given object implements the NodesClamavGetClamavResponseDataInner interface.
 */
export function instanceOfNodesClamavGetClamavResponseDataInner(value: object): value is NodesClamavGetClamavResponseDataInner {
    
    if (!('subdir' in value) || value['subdir'] === undefined) return false;
    
    return true;
}

export function NodesClamavGetClamavResponseDataInnerFromJSON(json: any): NodesClamavGetClamavResponseDataInner {
    return NodesClamavGetClamavResponseDataInnerFromJSONTyped(json, false);
}

export function NodesClamavGetClamavResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesClamavGetClamavResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'subdir': json['subdir'],
        
    };
}

export function NodesClamavGetClamavResponseDataInnerToJSON(json: any): NodesClamavGetClamavResponseDataInner {
    return NodesClamavGetClamavResponseDataInnerToJSONTyped(json, false);
}

export function NodesClamavGetClamavResponseDataInnerToJSONTyped(value?: NodesClamavGetClamavResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'subdir': value['subdir'],
        
    };
}

