/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgNodesPostfixActionEnum } from './PmgNodesPostfixActionEnum';
import {
    PmgNodesPostfixActionEnumFromJSON,
    PmgNodesPostfixActionEnumFromJSONTyped,
    PmgNodesPostfixActionEnumToJSON,
    PmgNodesPostfixActionEnumToJSONTyped,
} from './PmgNodesPostfixActionEnum';

/**
 * 
 * @export
 * @interface NodesPostfixQueueActionRequest
 */
export interface NodesPostfixQueueActionRequest {

    /**
     * Operation to perform on the given IDs.
     * @type {PmgNodesPostfixActionEnum}
     * @memberof NodesPostfixQueueActionRequest
     */
    action: PmgNodesPostfixActionEnum;

    /**
     * Queue ID(s).
     * @type {string}
     * @memberof NodesPostfixQueueActionRequest
     */
    ids: string;

}



/**
 * Check if a given object implements the NodesPostfixQueueActionRequest interface.
 */
export function instanceOfNodesPostfixQueueActionRequest(value: object): value is NodesPostfixQueueActionRequest {
    
    if (!('action' in value) || value['action'] === undefined) return false;
    
    if (!('ids' in value) || value['ids'] === undefined) return false;
    
    return true;
}

export function NodesPostfixQueueActionRequestFromJSON(json: any): NodesPostfixQueueActionRequest {
    return NodesPostfixQueueActionRequestFromJSONTyped(json, false);
}

export function NodesPostfixQueueActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesPostfixQueueActionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'action': PmgNodesPostfixActionEnumFromJSON(json['action']),
        
        'ids': json['ids'],
        
    };
}

export function NodesPostfixQueueActionRequestToJSON(json: any): NodesPostfixQueueActionRequest {
    return NodesPostfixQueueActionRequestToJSONTyped(json, false);
}

export function NodesPostfixQueueActionRequestToJSONTyped(value?: NodesPostfixQueueActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'action': PmgNodesPostfixActionEnumToJSON(value['action']),
        
        'ids': value['ids'],
        
    };
}

