/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface NodesAptChangeRepositoryRequest
 */
export interface NodesAptChangeRepositoryRequest {

    /**
     * Digest to detect modifications.
     * @type {string}
     * @memberof NodesAptChangeRepositoryRequest
     */
    digest?: string;

    /**
     * Whether the repository should be enabled or not.
     * @type {PmgBoolean}
     * @memberof NodesAptChangeRepositoryRequest
     */
    enabled?: PmgBoolean;

    /**
     * Index within the file (starting from 0).
     * @type {number}
     * @memberof NodesAptChangeRepositoryRequest
     */
    index: bigint | string | number;

    /**
     * Path to the containing file.
     * @type {string}
     * @memberof NodesAptChangeRepositoryRequest
     */
    path: string;

}



/**
 * Check if a given object implements the NodesAptChangeRepositoryRequest interface.
 */
export function instanceOfNodesAptChangeRepositoryRequest(value: object): value is NodesAptChangeRepositoryRequest {
    
    
    
    if (!('index' in value) || value['index'] === undefined) return false;
    
    if (!('path' in value) || value['path'] === undefined) return false;
    
    return true;
}

export function NodesAptChangeRepositoryRequestFromJSON(json: any): NodesAptChangeRepositoryRequest {
    return NodesAptChangeRepositoryRequestFromJSONTyped(json, false);
}

export function NodesAptChangeRepositoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesAptChangeRepositoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'enabled': json['enabled'] == null ? undefined : PmgBooleanFromJSON(json['enabled']),
        
        'index': BigInt(json['index']),
        
        'path': json['path'],
        
    };
}

export function NodesAptChangeRepositoryRequestToJSON(json: any): NodesAptChangeRepositoryRequest {
    return NodesAptChangeRepositoryRequestToJSONTyped(json, false);
}

export function NodesAptChangeRepositoryRequestToJSONTyped(value?: NodesAptChangeRepositoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'digest': value['digest'],
        
        'enabled': PmgBooleanToJSON(value['enabled']),
        
        'index': String(value['index']),
        
        'path': value['path'],
        
    };
}

