/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgNodesConfigAcmedomainField } from './PmgNodesConfigAcmedomainField';
import {
    PmgNodesConfigAcmedomainFieldFromJSON,
    PmgNodesConfigAcmedomainFieldFromJSONTyped,
    PmgNodesConfigAcmedomainFieldToJSON,
    PmgNodesConfigAcmedomainFieldToJSONTyped,
} from './PmgNodesConfigAcmedomainField';
import type { PmgNodesConfigAcmeField } from './PmgNodesConfigAcmeField';
import {
    PmgNodesConfigAcmeFieldFromJSON,
    PmgNodesConfigAcmeFieldFromJSONTyped,
    PmgNodesConfigAcmeFieldToJSON,
    PmgNodesConfigAcmeFieldToJSONTyped,
} from './PmgNodesConfigAcmeField';

/**
 * 
 * @export
 * @interface NodesConfigSetConfigRequest
 */
export interface NodesConfigSetConfigRequest {

    /**
     * Node specific ACME settings.
     * @type {PmgNodesConfigAcmeField}
     * @memberof NodesConfigSetConfigRequest
     */
    acme?: PmgNodesConfigAcmeField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain0?: PmgNodesConfigAcmedomainField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain1?: PmgNodesConfigAcmedomainField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain2?: PmgNodesConfigAcmedomainField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain3?: PmgNodesConfigAcmedomainField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain4?: PmgNodesConfigAcmedomainField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain5?: PmgNodesConfigAcmedomainField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain6?: PmgNodesConfigAcmedomainField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain7?: PmgNodesConfigAcmedomainField;

    /**
     * ACME domain and validation plugin
     * @type {PmgNodesConfigAcmedomainField}
     * @memberof NodesConfigSetConfigRequest
     */
    acmedomain8?: PmgNodesConfigAcmedomainField;

    /**
     * A list of settings you want to delete.
     * @type {string}
     * @memberof NodesConfigSetConfigRequest
     */
    _delete?: string;

    /**
     * Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof NodesConfigSetConfigRequest
     */
    digest?: string;

}

/**
 * Check if a given object implements the NodesConfigSetConfigRequest interface.
 */
export function instanceOfNodesConfigSetConfigRequest(value: object): value is NodesConfigSetConfigRequest {
    
    
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function NodesConfigSetConfigRequestFromJSON(json: any): NodesConfigSetConfigRequest {
    return NodesConfigSetConfigRequestFromJSONTyped(json, false);
}

export function NodesConfigSetConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesConfigSetConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'acme': json['acme'] == null ? undefined : PmgNodesConfigAcmeFieldFromJSON(json['acme']),
        
        'acmedomain0': json['acmedomain0'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain0']),
        
        'acmedomain1': json['acmedomain1'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain1']),
        
        'acmedomain2': json['acmedomain2'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain2']),
        
        'acmedomain3': json['acmedomain3'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain3']),
        
        'acmedomain4': json['acmedomain4'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain4']),
        
        'acmedomain5': json['acmedomain5'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain5']),
        
        'acmedomain6': json['acmedomain6'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain6']),
        
        'acmedomain7': json['acmedomain7'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain7']),
        
        'acmedomain8': json['acmedomain8'] == null ? undefined : PmgNodesConfigAcmedomainFieldFromJSON(json['acmedomain8']),
        
        '_delete': json['delete'] == null ? undefined : json['delete'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
    };
}

export function NodesConfigSetConfigRequestToJSON(json: any): NodesConfigSetConfigRequest {
    return NodesConfigSetConfigRequestToJSONTyped(json, false);
}

export function NodesConfigSetConfigRequestToJSONTyped(value?: NodesConfigSetConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'acme': PmgNodesConfigAcmeFieldToJSON(value['acme']),
        
        'acmedomain0': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain0']),
        
        'acmedomain1': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain1']),
        
        'acmedomain2': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain2']),
        
        'acmedomain3': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain3']),
        
        'acmedomain4': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain4']),
        
        'acmedomain5': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain5']),
        
        'acmedomain6': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain6']),
        
        'acmedomain7': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain7']),
        
        'acmedomain8': PmgNodesConfigAcmedomainFieldToJSON(value['acmedomain8']),
        
        'delete': value['_delete'],
        
        'digest': value['digest'],
        
    };
}

