/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesStatusStatusResponseDataBootInfo } from './NodesStatusStatusResponseDataBootInfo';
import {
    NodesStatusStatusResponseDataBootInfoFromJSON,
    NodesStatusStatusResponseDataBootInfoFromJSONTyped,
    NodesStatusStatusResponseDataBootInfoToJSON,
    NodesStatusStatusResponseDataBootInfoToJSONTyped,
} from './NodesStatusStatusResponseDataBootInfo';
import type { NodesStatusStatusResponseDataCurrentKernel } from './NodesStatusStatusResponseDataCurrentKernel';
import {
    NodesStatusStatusResponseDataCurrentKernelFromJSON,
    NodesStatusStatusResponseDataCurrentKernelFromJSONTyped,
    NodesStatusStatusResponseDataCurrentKernelToJSON,
    NodesStatusStatusResponseDataCurrentKernelToJSONTyped,
} from './NodesStatusStatusResponseDataCurrentKernel';
import type { PmgBoolean } from './PmgBoolean';
import {
    PmgBooleanFromJSON,
    PmgBooleanFromJSONTyped,
    PmgBooleanToJSON,
    PmgBooleanToJSONTyped,
} from './PmgBoolean';

/**
 * 
 * @export
 * @interface NodesStatusStatusResponseData
 */
export interface NodesStatusStatusResponseData {

    /**
     * 
     * @type {NodesStatusStatusResponseDataBootInfo}
     * @memberof NodesStatusStatusResponseData
     */
    bootInfo: NodesStatusStatusResponseDataBootInfo;

    /**
     * 
     * @type {NodesStatusStatusResponseDataCurrentKernel}
     * @memberof NodesStatusStatusResponseData
     */
    currentKernel: NodesStatusStatusResponseDataCurrentKernel;

    /**
     * Database is synced with other nodes.
     * @type {PmgBoolean}
     * @memberof NodesStatusStatusResponseData
     */
    insync: PmgBoolean;

    /**
     * Seconds since 1970-01-01 00:00:00 UTC.
     * @type {number}
     * @memberof NodesStatusStatusResponseData
     */
    time: bigint | string | number;

    /**
     * The uptime of the system in seconds.
     * @type {number}
     * @memberof NodesStatusStatusResponseData
     */
    uptime: bigint | string | number;

}



/**
 * Check if a given object implements the NodesStatusStatusResponseData interface.
 */
export function instanceOfNodesStatusStatusResponseData(value: object): value is NodesStatusStatusResponseData {
    
    if (!('bootInfo' in value) || value['bootInfo'] === undefined) return false;
    
    if (!('currentKernel' in value) || value['currentKernel'] === undefined) return false;
    
    if (!('insync' in value) || value['insync'] === undefined) return false;
    
    if (!('time' in value) || value['time'] === undefined) return false;
    
    if (!('uptime' in value) || value['uptime'] === undefined) return false;
    
    return true;
}

export function NodesStatusStatusResponseDataFromJSON(json: any): NodesStatusStatusResponseData {
    return NodesStatusStatusResponseDataFromJSONTyped(json, false);
}

export function NodesStatusStatusResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesStatusStatusResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'bootInfo': NodesStatusStatusResponseDataBootInfoFromJSON(json['boot-info']),
        
        'currentKernel': NodesStatusStatusResponseDataCurrentKernelFromJSON(json['current-kernel']),
        
        'insync': PmgBooleanFromJSON(json['insync']),
        
        'time': BigInt(json['time']),
        
        'uptime': BigInt(json['uptime']),
        
    };
}

export function NodesStatusStatusResponseDataToJSON(json: any): NodesStatusStatusResponseData {
    return NodesStatusStatusResponseDataToJSONTyped(json, false);
}

export function NodesStatusStatusResponseDataToJSONTyped(value?: NodesStatusStatusResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'boot-info': NodesStatusStatusResponseDataBootInfoToJSON(value['bootInfo']),
        
        'current-kernel': NodesStatusStatusResponseDataCurrentKernelToJSON(value['currentKernel']),
        
        'insync': PmgBooleanToJSON(value['insync']),
        
        'time': String(value['time']),
        
        'uptime': String(value['uptime']),
        
    };
}

