/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesPostfixMailqResponseDataInner
 */
export interface NodesPostfixMailqResponseDataInner {

    /**
     * URL slug of the child resource (inferred from PVE HATEOAS link).
     * @type {string}
     * @memberof NodesPostfixMailqResponseDataInner
     */
    queueId: string;

}

/**
 * Check if a given object implements the NodesPostfixMailqResponseDataInner interface.
 */
export function instanceOfNodesPostfixMailqResponseDataInner(value: object): value is NodesPostfixMailqResponseDataInner {
    
    if (!('queueId' in value) || value['queueId'] === undefined) return false;
    
    return true;
}

export function NodesPostfixMailqResponseDataInnerFromJSON(json: any): NodesPostfixMailqResponseDataInner {
    return NodesPostfixMailqResponseDataInnerFromJSONTyped(json, false);
}

export function NodesPostfixMailqResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesPostfixMailqResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'queueId': json['queue_id'],
        
    };
}

export function NodesPostfixMailqResponseDataInnerToJSON(json: any): NodesPostfixMailqResponseDataInner {
    return NodesPostfixMailqResponseDataInnerToJSONTyped(json, false);
}

export function NodesPostfixMailqResponseDataInnerToJSONTyped(value?: NodesPostfixMailqResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'queue_id': value['queueId'],
        
    };
}

