/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesAptListUpdatesResponse
 */
export interface NodesAptListUpdatesResponse {

    /**
     * 
     * @type {Array<object>}
     * @memberof NodesAptListUpdatesResponse
     */
    data: Array<object>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesAptListUpdatesResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesAptListUpdatesResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesAptListUpdatesResponse interface.
 */
export function instanceOfNodesAptListUpdatesResponse(value: object): value is NodesAptListUpdatesResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesAptListUpdatesResponseFromJSON(json: any): NodesAptListUpdatesResponse {
    return NodesAptListUpdatesResponseFromJSONTyped(json, false);
}

export function NodesAptListUpdatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesAptListUpdatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesAptListUpdatesResponseToJSON(json: any): NodesAptListUpdatesResponse {
    return NodesAptListUpdatesResponseToJSONTyped(json, false);
}

export function NodesAptListUpdatesResponseToJSONTyped(value?: NodesAptListUpdatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

