/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesPostfixMailqResponseDataInner } from './NodesPostfixMailqResponseDataInner';
import {
    NodesPostfixMailqResponseDataInnerFromJSON,
    NodesPostfixMailqResponseDataInnerFromJSONTyped,
    NodesPostfixMailqResponseDataInnerToJSON,
    NodesPostfixMailqResponseDataInnerToJSONTyped,
} from './NodesPostfixMailqResponseDataInner';

/**
 * 
 * @export
 * @interface NodesPostfixMailqResponse
 */
export interface NodesPostfixMailqResponse {

    /**
     * 
     * @type {Array<NodesPostfixMailqResponseDataInner>}
     * @memberof NodesPostfixMailqResponse
     */
    data: Array<NodesPostfixMailqResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesPostfixMailqResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesPostfixMailqResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesPostfixMailqResponse interface.
 */
export function instanceOfNodesPostfixMailqResponse(value: object): value is NodesPostfixMailqResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesPostfixMailqResponseFromJSON(json: any): NodesPostfixMailqResponse {
    return NodesPostfixMailqResponseFromJSONTyped(json, false);
}

export function NodesPostfixMailqResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesPostfixMailqResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(NodesPostfixMailqResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesPostfixMailqResponseToJSON(json: any): NodesPostfixMailqResponse {
    return NodesPostfixMailqResponseToJSONTyped(json, false);
}

export function NodesPostfixMailqResponseToJSONTyped(value?: NodesPostfixMailqResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(NodesPostfixMailqResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

