/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigPbsGetPbsResponseDataInner } from './ConfigPbsGetPbsResponseDataInner';
import {
    ConfigPbsGetPbsResponseDataInnerFromJSON,
    ConfigPbsGetPbsResponseDataInnerFromJSONTyped,
    ConfigPbsGetPbsResponseDataInnerToJSON,
    ConfigPbsGetPbsResponseDataInnerToJSONTyped,
} from './ConfigPbsGetPbsResponseDataInner';

/**
 * 
 * @export
 * @interface NodesPbsGetPbsResponse
 */
export interface NodesPbsGetPbsResponse {

    /**
     * 
     * @type {Array<ConfigPbsGetPbsResponseDataInner>}
     * @memberof NodesPbsGetPbsResponse
     */
    data: Array<ConfigPbsGetPbsResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesPbsGetPbsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesPbsGetPbsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesPbsGetPbsResponse interface.
 */
export function instanceOfNodesPbsGetPbsResponse(value: object): value is NodesPbsGetPbsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesPbsGetPbsResponseFromJSON(json: any): NodesPbsGetPbsResponse {
    return NodesPbsGetPbsResponseFromJSONTyped(json, false);
}

export function NodesPbsGetPbsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesPbsGetPbsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ConfigPbsGetPbsResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesPbsGetPbsResponseToJSON(json: any): NodesPbsGetPbsResponse {
    return NodesPbsGetPbsResponseToJSONTyped(json, false);
}

export function NodesPbsGetPbsResponseToJSONTyped(value?: NodesPbsGetPbsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ConfigPbsGetPbsResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

