/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesBackupRestoreResponse
 */
export interface NodesBackupRestoreResponse {

    /**
     * 
     * @type {string}
     * @memberof NodesBackupRestoreResponse
     */
    data: string;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesBackupRestoreResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesBackupRestoreResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesBackupRestoreResponse interface.
 */
export function instanceOfNodesBackupRestoreResponse(value: object): value is NodesBackupRestoreResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesBackupRestoreResponseFromJSON(json: any): NodesBackupRestoreResponse {
    return NodesBackupRestoreResponseFromJSONTyped(json, false);
}

export function NodesBackupRestoreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesBackupRestoreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesBackupRestoreResponseToJSON(json: any): NodesBackupRestoreResponse {
    return NodesBackupRestoreResponseToJSONTyped(json, false);
}

export function NodesBackupRestoreResponseToJSONTyped(value?: NodesBackupRestoreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

