/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesNetworkGetNetworkResponseDataInner } from './NodesNetworkGetNetworkResponseDataInner';
import {
    NodesNetworkGetNetworkResponseDataInnerFromJSON,
    NodesNetworkGetNetworkResponseDataInnerFromJSONTyped,
    NodesNetworkGetNetworkResponseDataInnerToJSON,
    NodesNetworkGetNetworkResponseDataInnerToJSONTyped,
} from './NodesNetworkGetNetworkResponseDataInner';

/**
 * 
 * @export
 * @interface NodesNetworkGetNetworkResponse
 */
export interface NodesNetworkGetNetworkResponse {

    /**
     * 
     * @type {Array<NodesNetworkGetNetworkResponseDataInner>}
     * @memberof NodesNetworkGetNetworkResponse
     */
    data: Array<NodesNetworkGetNetworkResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesNetworkGetNetworkResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesNetworkGetNetworkResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesNetworkGetNetworkResponse interface.
 */
export function instanceOfNodesNetworkGetNetworkResponse(value: object): value is NodesNetworkGetNetworkResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesNetworkGetNetworkResponseFromJSON(json: any): NodesNetworkGetNetworkResponse {
    return NodesNetworkGetNetworkResponseFromJSONTyped(json, false);
}

export function NodesNetworkGetNetworkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesNetworkGetNetworkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(NodesNetworkGetNetworkResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesNetworkGetNetworkResponseToJSON(json: any): NodesNetworkGetNetworkResponse {
    return NodesNetworkGetNetworkResponseToJSONTyped(json, false);
}

export function NodesNetworkGetNetworkResponseToJSONTyped(value?: NodesNetworkGetNetworkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(NodesNetworkGetNetworkResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

