/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesVncwebsocketResponseData
 */
export interface NodesVncwebsocketResponseData {

    /**
     * 
     * @type {string}
     * @memberof NodesVncwebsocketResponseData
     */
    port: string;

}

/**
 * Check if a given object implements the NodesVncwebsocketResponseData interface.
 */
export function instanceOfNodesVncwebsocketResponseData(value: object): value is NodesVncwebsocketResponseData {
    
    if (!('port' in value) || value['port'] === undefined) return false;
    
    return true;
}

export function NodesVncwebsocketResponseDataFromJSON(json: any): NodesVncwebsocketResponseData {
    return NodesVncwebsocketResponseDataFromJSONTyped(json, false);
}

export function NodesVncwebsocketResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesVncwebsocketResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'port': json['port'],
        
    };
}

export function NodesVncwebsocketResponseDataToJSON(json: any): NodesVncwebsocketResponseData {
    return NodesVncwebsocketResponseDataToJSONTyped(json, false);
}

export function NodesVncwebsocketResponseDataToJSONTyped(value?: NodesVncwebsocketResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'port': value['port'],
        
    };
}

