/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesPbsListTimerResponseData } from './NodesPbsListTimerResponseData';
import {
    NodesPbsListTimerResponseDataFromJSON,
    NodesPbsListTimerResponseDataFromJSONTyped,
    NodesPbsListTimerResponseDataToJSON,
    NodesPbsListTimerResponseDataToJSONTyped,
} from './NodesPbsListTimerResponseData';

/**
 * 
 * @export
 * @interface NodesPbsListTimerResponse
 */
export interface NodesPbsListTimerResponse {

    /**
     * 
     * @type {NodesPbsListTimerResponseData}
     * @memberof NodesPbsListTimerResponse
     */
    data: NodesPbsListTimerResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesPbsListTimerResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesPbsListTimerResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesPbsListTimerResponse interface.
 */
export function instanceOfNodesPbsListTimerResponse(value: object): value is NodesPbsListTimerResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesPbsListTimerResponseFromJSON(json: any): NodesPbsListTimerResponse {
    return NodesPbsListTimerResponseFromJSONTyped(json, false);
}

export function NodesPbsListTimerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesPbsListTimerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': NodesPbsListTimerResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesPbsListTimerResponseToJSON(json: any): NodesPbsListTimerResponse {
    return NodesPbsListTimerResponseToJSONTyped(json, false);
}

export function NodesPbsListTimerResponseToJSONTyped(value?: NodesPbsListTimerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': NodesPbsListTimerResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

