/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesTrackerMaillogResponseData
 */
export interface NodesTrackerMaillogResponseData {

    /**
     * Client address
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    client?: string;

    /**
     * Delivery status.
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    dstatus: string;

    /**
     * Sender email address.
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    from: string;

    /**
     * Unique ID.
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    id: string;

    /**
     * 
     * @type {Array<string>}
     * @memberof NodesTrackerMaillogResponseData
     */
    logs: Array<string>;

    /**
     * SMTP message ID.
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    msgid?: string;

    /**
     * Postfix qmgr ID.
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    qid?: string;

    /**
     * ID of relayed mail.
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    relay?: string;

    /**
     * Delivery status of relayed mail.
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    rstatus?: string;

    /**
     * The size of the raw email.
     * @type {number}
     * @memberof NodesTrackerMaillogResponseData
     */
    size?: number;

    /**
     * Delivery timestamp.
     * @type {number}
     * @memberof NodesTrackerMaillogResponseData
     */
    time: bigint | string | number;

    /**
     * Receiver email address.
     * @type {string}
     * @memberof NodesTrackerMaillogResponseData
     */
    to: string;

}

/**
 * Check if a given object implements the NodesTrackerMaillogResponseData interface.
 */
export function instanceOfNodesTrackerMaillogResponseData(value: object): value is NodesTrackerMaillogResponseData {
    
    
    if (!('dstatus' in value) || value['dstatus'] === undefined) return false;
    
    if (!('from' in value) || value['from'] === undefined) return false;
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('logs' in value) || value['logs'] === undefined) return false;
    
    
    
    
    
    
    if (!('time' in value) || value['time'] === undefined) return false;
    
    if (!('to' in value) || value['to'] === undefined) return false;
    
    return true;
}

export function NodesTrackerMaillogResponseDataFromJSON(json: any): NodesTrackerMaillogResponseData {
    return NodesTrackerMaillogResponseDataFromJSONTyped(json, false);
}

export function NodesTrackerMaillogResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesTrackerMaillogResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'client': json['client'] == null ? undefined : json['client'],
        
        'dstatus': json['dstatus'],
        
        'from': json['from'],
        
        'id': json['id'],
        
        'logs': json['logs'],
        
        'msgid': json['msgid'] == null ? undefined : json['msgid'],
        
        'qid': json['qid'] == null ? undefined : json['qid'],
        
        'relay': json['relay'] == null ? undefined : json['relay'],
        
        'rstatus': json['rstatus'] == null ? undefined : json['rstatus'],
        
        'size': json['size'] == null ? undefined : json['size'],
        
        'time': BigInt(json['time']),
        
        'to': json['to'],
        
    };
}

export function NodesTrackerMaillogResponseDataToJSON(json: any): NodesTrackerMaillogResponseData {
    return NodesTrackerMaillogResponseDataToJSONTyped(json, false);
}

export function NodesTrackerMaillogResponseDataToJSONTyped(value?: NodesTrackerMaillogResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'client': value['client'],
        
        'dstatus': value['dstatus'],
        
        'from': value['from'],
        
        'id': value['id'],
        
        'logs': value['logs'],
        
        'msgid': value['msgid'],
        
        'qid': value['qid'],
        
        'relay': value['relay'],
        
        'rstatus': value['rstatus'],
        
        'size': value['size'],
        
        'time': String(value['time']),
        
        'to': value['to'],
        
    };
}

