/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PmgAutocreateRoleEnum } from './PmgAutocreateRoleEnum';
import {
    PmgAutocreateRoleEnumFromJSON,
    PmgAutocreateRoleEnumFromJSONTyped,
    PmgAutocreateRoleEnumToJSON,
    PmgAutocreateRoleEnumToJSONTyped,
} from './PmgAutocreateRoleEnum';
import type { PmgSourceEnum } from './PmgSourceEnum';
import {
    PmgSourceEnumFromJSON,
    PmgSourceEnumFromJSONTyped,
    PmgSourceEnumToJSON,
    PmgSourceEnumToJSONTyped,
} from './PmgSourceEnum';

/**
 * 
 * @export
 * @interface PmgAutocreateRoleAssignmentConfig
 */
export interface PmgAutocreateRoleAssignmentConfig {

    /**
     * The fixed role that should be assigned to auto-created users.
     * @type {PmgAutocreateRoleEnum}
     * @memberof PmgAutocreateRoleAssignmentConfig
     */
    fixedRole?: PmgAutocreateRoleEnum;

    /**
     * OIDC claim used to assign the unique username.
     * @type {string}
     * @memberof PmgAutocreateRoleAssignmentConfig
     */
    roleClaim?: string;

    /**
     * How the access role for a newly auto-created user should be selected.
     * @type {PmgSourceEnum}
     * @memberof PmgAutocreateRoleAssignmentConfig
     */
    source: PmgSourceEnum;

}



/**
 * Check if a given object implements the PmgAutocreateRoleAssignmentConfig interface.
 */
export function instanceOfPmgAutocreateRoleAssignmentConfig(value: object): value is PmgAutocreateRoleAssignmentConfig {
    
    
    
    if (!('source' in value) || value['source'] === undefined) return false;
    
    return true;
}

export function PmgAutocreateRoleAssignmentConfigFromJSON(json: any): PmgAutocreateRoleAssignmentConfig {
    return PmgAutocreateRoleAssignmentConfigFromJSONTyped(json, false);
}

export function PmgAutocreateRoleAssignmentConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgAutocreateRoleAssignmentConfig {
    if (json == null) {
        return json;
    }
    return {
        
        
        'fixedRole': json['fixed-role'] == null ? undefined : PmgAutocreateRoleEnumFromJSON(json['fixed-role']),
        
        'roleClaim': json['role-claim'] == null ? undefined : json['role-claim'],
        
        'source': PmgSourceEnumFromJSON(json['source']),
        
    };
}

export function PmgAutocreateRoleAssignmentConfigToJSON(json: any): PmgAutocreateRoleAssignmentConfig {
    return PmgAutocreateRoleAssignmentConfigToJSONTyped(json, false);
}

export function PmgAutocreateRoleAssignmentConfigToJSONTyped(value?: PmgAutocreateRoleAssignmentConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'fixed-role': PmgAutocreateRoleEnumToJSON(value['fixedRole']),
        
        'role-claim': value['roleClaim'],
        
        'source': PmgSourceEnumToJSON(value['source']),
        
    };
}

