/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgConfigAdminDkimUseDomainEnum = {
    Header: 'header',
    Envelope: 'envelope'
} as const;
export type PmgConfigAdminDkimUseDomainEnum = typeof PmgConfigAdminDkimUseDomainEnum[keyof typeof PmgConfigAdminDkimUseDomainEnum];


export function instanceOfPmgConfigAdminDkimUseDomainEnum(value: any): boolean {
    for (const key in PmgConfigAdminDkimUseDomainEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgConfigAdminDkimUseDomainEnum, key)) {
            if (PmgConfigAdminDkimUseDomainEnum[key as keyof typeof PmgConfigAdminDkimUseDomainEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgConfigAdminDkimUseDomainEnumFromJSON(json: any): PmgConfigAdminDkimUseDomainEnum {
    return PmgConfigAdminDkimUseDomainEnumFromJSONTyped(json, false);
}

export function PmgConfigAdminDkimUseDomainEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgConfigAdminDkimUseDomainEnum {
    return json as PmgConfigAdminDkimUseDomainEnum;
}

export function PmgConfigAdminDkimUseDomainEnumToJSON(value?: PmgConfigAdminDkimUseDomainEnum | null): any {
    return value as any;
}

export function PmgConfigAdminDkimUseDomainEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgConfigAdminDkimUseDomainEnum {
    return value as PmgConfigAdminDkimUseDomainEnum;
}

