/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgConfigRuledbModeEnum = {
    Any: 'any',
    None: 'none',
    Group: 'group'
} as const;
export type PmgConfigRuledbModeEnum = typeof PmgConfigRuledbModeEnum[keyof typeof PmgConfigRuledbModeEnum];


export function instanceOfPmgConfigRuledbModeEnum(value: any): boolean {
    for (const key in PmgConfigRuledbModeEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgConfigRuledbModeEnum, key)) {
            if (PmgConfigRuledbModeEnum[key as keyof typeof PmgConfigRuledbModeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgConfigRuledbModeEnumFromJSON(json: any): PmgConfigRuledbModeEnum {
    return PmgConfigRuledbModeEnumFromJSONTyped(json, false);
}

export function PmgConfigRuledbModeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgConfigRuledbModeEnum {

    return json as PmgConfigRuledbModeEnum;

}

export function PmgConfigRuledbModeEnumToJSON(value?: PmgConfigRuledbModeEnum | null): any {
    return value as any;
}

export function PmgConfigRuledbModeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgConfigRuledbModeEnum {
    return value as PmgConfigRuledbModeEnum;
}

