/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgConfigSpamquarReportstyleEnum = {
    None: 'none',
    Short: 'short',
    Verbose: 'verbose',
    Custom: 'custom'
} as const;
export type PmgConfigSpamquarReportstyleEnum = typeof PmgConfigSpamquarReportstyleEnum[keyof typeof PmgConfigSpamquarReportstyleEnum];


export function instanceOfPmgConfigSpamquarReportstyleEnum(value: any): boolean {
    for (const key in PmgConfigSpamquarReportstyleEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgConfigSpamquarReportstyleEnum, key)) {
            if (PmgConfigSpamquarReportstyleEnum[key as keyof typeof PmgConfigSpamquarReportstyleEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgConfigSpamquarReportstyleEnumFromJSON(json: any): PmgConfigSpamquarReportstyleEnum {
    return PmgConfigSpamquarReportstyleEnumFromJSONTyped(json, false);
}

export function PmgConfigSpamquarReportstyleEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgConfigSpamquarReportstyleEnum {

    return json as PmgConfigSpamquarReportstyleEnum;

}

export function PmgConfigSpamquarReportstyleEnumToJSON(value?: PmgConfigSpamquarReportstyleEnum | null): any {
    return value as any;
}

export function PmgConfigSpamquarReportstyleEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgConfigSpamquarReportstyleEnum {
    return value as PmgConfigSpamquarReportstyleEnum;
}

