/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgNodesTasksStatusEnum = {
    Running: 'running',
    Stopped: 'stopped'
} as const;
export type PmgNodesTasksStatusEnum = typeof PmgNodesTasksStatusEnum[keyof typeof PmgNodesTasksStatusEnum];


export function instanceOfPmgNodesTasksStatusEnum(value: any): boolean {
    for (const key in PmgNodesTasksStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgNodesTasksStatusEnum, key)) {
            if (PmgNodesTasksStatusEnum[key as keyof typeof PmgNodesTasksStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgNodesTasksStatusEnumFromJSON(json: any): PmgNodesTasksStatusEnum {
    return PmgNodesTasksStatusEnumFromJSONTyped(json, false);
}

export function PmgNodesTasksStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgNodesTasksStatusEnum {

    return json as PmgNodesTasksStatusEnum;

}

export function PmgNodesTasksStatusEnumToJSON(value?: PmgNodesTasksStatusEnum | null): any {
    return value as any;
}

export function PmgNodesTasksStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgNodesTasksStatusEnum {
    return value as PmgNodesTasksStatusEnum;
}

