/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgNodesTimeframeEnum = {
    Hour: 'hour',
    Day: 'day',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type PmgNodesTimeframeEnum = typeof PmgNodesTimeframeEnum[keyof typeof PmgNodesTimeframeEnum];


export function instanceOfPmgNodesTimeframeEnum(value: any): boolean {
    for (const key in PmgNodesTimeframeEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgNodesTimeframeEnum, key)) {
            if (PmgNodesTimeframeEnum[key as keyof typeof PmgNodesTimeframeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgNodesTimeframeEnumFromJSON(json: any): PmgNodesTimeframeEnum {
    return PmgNodesTimeframeEnumFromJSONTyped(json, false);
}

export function PmgNodesTimeframeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgNodesTimeframeEnum {

    return json as PmgNodesTimeframeEnum;

}

export function PmgNodesTimeframeEnumToJSON(value?: PmgNodesTimeframeEnum | null): any {
    return value as any;
}

export function PmgNodesTimeframeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgNodesTimeframeEnum {
    return value as PmgNodesTimeframeEnum;
}

