/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgNodesStatusModeEnum = {
    Efi: 'efi',
    LegacyBios: 'legacy-bios'
} as const;
export type PmgNodesStatusModeEnum = typeof PmgNodesStatusModeEnum[keyof typeof PmgNodesStatusModeEnum];


export function instanceOfPmgNodesStatusModeEnum(value: any): boolean {
    for (const key in PmgNodesStatusModeEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgNodesStatusModeEnum, key)) {
            if (PmgNodesStatusModeEnum[key as keyof typeof PmgNodesStatusModeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgNodesStatusModeEnumFromJSON(json: any): PmgNodesStatusModeEnum {
    return PmgNodesStatusModeEnumFromJSONTyped(json, false);
}

export function PmgNodesStatusModeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgNodesStatusModeEnum {
    return json as PmgNodesStatusModeEnum;
}

export function PmgNodesStatusModeEnumToJSON(value?: PmgNodesStatusModeEnum | null): any {
    return value as any;
}

export function PmgNodesStatusModeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgNodesStatusModeEnum {
    return value as PmgNodesStatusModeEnum;
}

