/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgNodesPostfixSortdirEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type PmgNodesPostfixSortdirEnum = typeof PmgNodesPostfixSortdirEnum[keyof typeof PmgNodesPostfixSortdirEnum];


export function instanceOfPmgNodesPostfixSortdirEnum(value: any): boolean {
    for (const key in PmgNodesPostfixSortdirEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgNodesPostfixSortdirEnum, key)) {
            if (PmgNodesPostfixSortdirEnum[key as keyof typeof PmgNodesPostfixSortdirEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgNodesPostfixSortdirEnumFromJSON(json: any): PmgNodesPostfixSortdirEnum {
    return PmgNodesPostfixSortdirEnumFromJSONTyped(json, false);
}

export function PmgNodesPostfixSortdirEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgNodesPostfixSortdirEnum {
    return json as PmgNodesPostfixSortdirEnum;
}

export function PmgNodesPostfixSortdirEnumToJSON(value?: PmgNodesPostfixSortdirEnum | null): any {
    return value as any;
}

export function PmgNodesPostfixSortdirEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgNodesPostfixSortdirEnum {
    return value as PmgNodesPostfixSortdirEnum;
}

