/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgPositionEnum = {
    Start: 'start',
    End: 'end'
} as const;
export type PmgPositionEnum = typeof PmgPositionEnum[keyof typeof PmgPositionEnum];


export function instanceOfPmgPositionEnum(value: any): boolean {
    for (const key in PmgPositionEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgPositionEnum, key)) {
            if (PmgPositionEnum[key as keyof typeof PmgPositionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgPositionEnumFromJSON(json: any): PmgPositionEnum {
    return PmgPositionEnumFromJSONTyped(json, false);
}

export function PmgPositionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgPositionEnum {

    return json as PmgPositionEnum;

}

export function PmgPositionEnumToJSON(value?: PmgPositionEnum | null): any {
    return value as any;
}

export function PmgPositionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgPositionEnum {
    return value as PmgPositionEnum;
}

