/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgProtocolEnum = {
    Pop3: 'pop3',
    Imap: 'imap'
} as const;
export type PmgProtocolEnum = typeof PmgProtocolEnum[keyof typeof PmgProtocolEnum];


export function instanceOfPmgProtocolEnum(value: any): boolean {
    for (const key in PmgProtocolEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgProtocolEnum, key)) {
            if (PmgProtocolEnum[key as keyof typeof PmgProtocolEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgProtocolEnumFromJSON(json: any): PmgProtocolEnum {
    return PmgProtocolEnumFromJSONTyped(json, false);
}

export function PmgProtocolEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgProtocolEnum {
    return json as PmgProtocolEnum;
}

export function PmgProtocolEnumToJSON(value?: PmgProtocolEnum | null): any {
    return value as any;
}

export function PmgProtocolEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgProtocolEnum {
    return value as PmgProtocolEnum;
}

