/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgQuarantineListEnum = {
    Bl: 'BL',
    Wl: 'WL'
} as const;
export type PmgQuarantineListEnum = typeof PmgQuarantineListEnum[keyof typeof PmgQuarantineListEnum];


export function instanceOfPmgQuarantineListEnum(value: any): boolean {
    for (const key in PmgQuarantineListEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgQuarantineListEnum, key)) {
            if (PmgQuarantineListEnum[key as keyof typeof PmgQuarantineListEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgQuarantineListEnumFromJSON(json: any): PmgQuarantineListEnum {
    return PmgQuarantineListEnumFromJSONTyped(json, false);
}

export function PmgQuarantineListEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgQuarantineListEnum {

    return json as PmgQuarantineListEnum;

}

export function PmgQuarantineListEnumToJSON(value?: PmgQuarantineListEnum | null): any {
    return value as any;
}

export function PmgQuarantineListEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgQuarantineListEnum {
    return value as PmgQuarantineListEnum;
}

