/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgTypeEnum = {
    Totp: 'totp',
    U2f: 'u2f',
    Webauthn: 'webauthn',
    Recovery: 'recovery'
} as const;
export type PmgTypeEnum = typeof PmgTypeEnum[keyof typeof PmgTypeEnum];


export function instanceOfPmgTypeEnum(value: any): boolean {
    for (const key in PmgTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgTypeEnum, key)) {
            if (PmgTypeEnum[key as keyof typeof PmgTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgTypeEnumFromJSON(json: any): PmgTypeEnum {
    return PmgTypeEnumFromJSONTyped(json, false);
}

export function PmgTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgTypeEnum {

    return json as PmgTypeEnum;

}

export function PmgTypeEnumToJSON(value?: PmgTypeEnum | null): any {
    return value as any;
}

export function PmgTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgTypeEnum {
    return value as PmgTypeEnum;
}

