/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PmgTypeTypeEnum = {
    Bridge: 'bridge',
    Bond: 'bond',
    Eth: 'eth',
    Alias: 'alias',
    Vlan: 'vlan',
    OvsBridge: 'OVSBridge',
    OvsBond: 'OVSBond',
    OvsPort: 'OVSPort',
    OvsIntPort: 'OVSIntPort',
    Unknown: 'unknown'
} as const;
export type PmgTypeTypeEnum = typeof PmgTypeTypeEnum[keyof typeof PmgTypeTypeEnum];


export function instanceOfPmgTypeTypeEnum(value: any): boolean {
    for (const key in PmgTypeTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PmgTypeTypeEnum, key)) {
            if (PmgTypeTypeEnum[key as keyof typeof PmgTypeTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PmgTypeTypeEnumFromJSON(json: any): PmgTypeTypeEnum {
    return PmgTypeTypeEnumFromJSONTyped(json, false);
}

export function PmgTypeTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PmgTypeTypeEnum {

    return json as PmgTypeTypeEnum;

}

export function PmgTypeTypeEnumToJSON(value?: PmgTypeTypeEnum | null): any {
    return value as any;
}

export function PmgTypeTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PmgTypeTypeEnum {
    return value as PmgTypeTypeEnum;
}

