/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuarantineBlacklistBlacklistResponseDataInner } from './QuarantineBlacklistBlacklistResponseDataInner';
import {
    QuarantineBlacklistBlacklistResponseDataInnerFromJSON,
    QuarantineBlacklistBlacklistResponseDataInnerFromJSONTyped,
    QuarantineBlacklistBlacklistResponseDataInnerToJSON,
    QuarantineBlacklistBlacklistResponseDataInnerToJSONTyped,
} from './QuarantineBlacklistBlacklistResponseDataInner';

/**
 * 
 * @export
 * @interface QuarantineBlacklistBlacklistResponse
 */
export interface QuarantineBlacklistBlacklistResponse {

    /**
     * 
     * @type {Array<QuarantineBlacklistBlacklistResponseDataInner>}
     * @memberof QuarantineBlacklistBlacklistResponse
     */
    data: Array<QuarantineBlacklistBlacklistResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof QuarantineBlacklistBlacklistResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof QuarantineBlacklistBlacklistResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the QuarantineBlacklistBlacklistResponse interface.
 */
export function instanceOfQuarantineBlacklistBlacklistResponse(value: object): value is QuarantineBlacklistBlacklistResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function QuarantineBlacklistBlacklistResponseFromJSON(json: any): QuarantineBlacklistBlacklistResponse {
    return QuarantineBlacklistBlacklistResponseFromJSONTyped(json, false);
}

export function QuarantineBlacklistBlacklistResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuarantineBlacklistBlacklistResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(QuarantineBlacklistBlacklistResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function QuarantineBlacklistBlacklistResponseToJSON(json: any): QuarantineBlacklistBlacklistResponse {
    return QuarantineBlacklistBlacklistResponseToJSONTyped(json, false);
}

export function QuarantineBlacklistBlacklistResponseToJSONTyped(value?: QuarantineBlacklistBlacklistResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(QuarantineBlacklistBlacklistResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

