/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuarantineQuarusersResponseDataInner } from './QuarantineQuarusersResponseDataInner';
import {
    QuarantineQuarusersResponseDataInnerFromJSON,
    QuarantineQuarusersResponseDataInnerFromJSONTyped,
    QuarantineQuarusersResponseDataInnerToJSON,
    QuarantineQuarusersResponseDataInnerToJSONTyped,
} from './QuarantineQuarusersResponseDataInner';

/**
 * 
 * @export
 * @interface QuarantineQuarusersResponse
 */
export interface QuarantineQuarusersResponse {

    /**
     * 
     * @type {Array<QuarantineQuarusersResponseDataInner>}
     * @memberof QuarantineQuarusersResponse
     */
    data: Array<QuarantineQuarusersResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof QuarantineQuarusersResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof QuarantineQuarusersResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the QuarantineQuarusersResponse interface.
 */
export function instanceOfQuarantineQuarusersResponse(value: object): value is QuarantineQuarusersResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function QuarantineQuarusersResponseFromJSON(json: any): QuarantineQuarusersResponse {
    return QuarantineQuarusersResponseFromJSONTyped(json, false);
}

export function QuarantineQuarusersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuarantineQuarusersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(QuarantineQuarusersResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function QuarantineQuarusersResponseToJSON(json: any): QuarantineQuarusersResponse {
    return QuarantineQuarusersResponseToJSONTyped(json, false);
}

export function QuarantineQuarusersResponseToJSONTyped(value?: QuarantineQuarusersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(QuarantineQuarusersResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

