/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuarantineVirusstatusResponseData
 */
export interface QuarantineVirusstatusResponseData {

    /**
     * Average size of stored mails in bytes.
     * @type {number}
     * @memberof QuarantineVirusstatusResponseData
     */
    avgbytes: number;

    /**
     * Number of stored mails.
     * @type {number}
     * @memberof QuarantineVirusstatusResponseData
     */
    count: number;

    /**
     * Estimated disk space usage in MByte.
     * @type {number}
     * @memberof QuarantineVirusstatusResponseData
     */
    mbytes: number;

}

/**
 * Check if a given object implements the QuarantineVirusstatusResponseData interface.
 */
export function instanceOfQuarantineVirusstatusResponseData(value: object): value is QuarantineVirusstatusResponseData {
    
    if (!('avgbytes' in value) || value['avgbytes'] === undefined) return false;
    
    if (!('count' in value) || value['count'] === undefined) return false;
    
    if (!('mbytes' in value) || value['mbytes'] === undefined) return false;
    
    return true;
}

export function QuarantineVirusstatusResponseDataFromJSON(json: any): QuarantineVirusstatusResponseData {
    return QuarantineVirusstatusResponseDataFromJSONTyped(json, false);
}

export function QuarantineVirusstatusResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuarantineVirusstatusResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'avgbytes': json['avgbytes'],
        
        'count': json['count'],
        
        'mbytes': json['mbytes'],
        
    };
}

export function QuarantineVirusstatusResponseDataToJSON(json: any): QuarantineVirusstatusResponseData {
    return QuarantineVirusstatusResponseDataToJSONTyped(json, false);
}

export function QuarantineVirusstatusResponseDataToJSONTyped(value?: QuarantineVirusstatusResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'avgbytes': value['avgbytes'],
        
        'count': value['count'],
        
        'mbytes': value['mbytes'],
        
    };
}

