/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuarantineSpamstatusResponseData } from './QuarantineSpamstatusResponseData';
import {
    QuarantineSpamstatusResponseDataFromJSON,
    QuarantineSpamstatusResponseDataFromJSONTyped,
    QuarantineSpamstatusResponseDataToJSON,
    QuarantineSpamstatusResponseDataToJSONTyped,
} from './QuarantineSpamstatusResponseData';

/**
 * 
 * @export
 * @interface QuarantineSpamstatusResponse
 */
export interface QuarantineSpamstatusResponse {

    /**
     * 
     * @type {QuarantineSpamstatusResponseData}
     * @memberof QuarantineSpamstatusResponse
     */
    data: QuarantineSpamstatusResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof QuarantineSpamstatusResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof QuarantineSpamstatusResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the QuarantineSpamstatusResponse interface.
 */
export function instanceOfQuarantineSpamstatusResponse(value: object): value is QuarantineSpamstatusResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function QuarantineSpamstatusResponseFromJSON(json: any): QuarantineSpamstatusResponse {
    return QuarantineSpamstatusResponseFromJSONTyped(json, false);
}

export function QuarantineSpamstatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuarantineSpamstatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': QuarantineSpamstatusResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function QuarantineSpamstatusResponseToJSON(json: any): QuarantineSpamstatusResponse {
    return QuarantineSpamstatusResponseToJSONTyped(json, false);
}

export function QuarantineSpamstatusResponseToJSONTyped(value?: QuarantineSpamstatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': QuarantineSpamstatusResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

