/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatisticsContactResponseDataInner } from './StatisticsContactResponseDataInner';
import {
    StatisticsContactResponseDataInnerFromJSON,
    StatisticsContactResponseDataInnerFromJSONTyped,
    StatisticsContactResponseDataInnerToJSON,
    StatisticsContactResponseDataInnerToJSONTyped,
} from './StatisticsContactResponseDataInner';

/**
 * 
 * @export
 * @interface StatisticsContactResponse
 */
export interface StatisticsContactResponse {

    /**
     * 
     * @type {Array<StatisticsContactResponseDataInner>}
     * @memberof StatisticsContactResponse
     */
    data: Array<StatisticsContactResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof StatisticsContactResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof StatisticsContactResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the StatisticsContactResponse interface.
 */
export function instanceOfStatisticsContactResponse(value: object): value is StatisticsContactResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function StatisticsContactResponseFromJSON(json: any): StatisticsContactResponse {
    return StatisticsContactResponseFromJSONTyped(json, false);
}

export function StatisticsContactResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticsContactResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(StatisticsContactResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function StatisticsContactResponseToJSON(json: any): StatisticsContactResponse {
    return StatisticsContactResponseToJSONTyped(json, false);
}

export function StatisticsContactResponseToJSONTyped(value?: StatisticsContactResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(StatisticsContactResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

