/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatisticsReceiverResponseDataInner
 */
export interface StatisticsReceiverResponseDataInner {

    /**
     * Mail traffic (Bytes).
     * @type {number}
     * @memberof StatisticsReceiverResponseDataInner
     */
    bytes: number;

    /**
     * Mail count.
     * @type {number}
     * @memberof StatisticsReceiverResponseDataInner
     */
    count?: number;

    /**
     * Sender email.
     * @type {string}
     * @memberof StatisticsReceiverResponseDataInner
     */
    receiver: string;

    /**
     * Number of sent spam mails.
     * @type {number}
     * @memberof StatisticsReceiverResponseDataInner
     */
    spamcount?: number;

    /**
     * Number of sent virus mails.
     * @type {number}
     * @memberof StatisticsReceiverResponseDataInner
     */
    viruscount?: number;

}

/**
 * Check if a given object implements the StatisticsReceiverResponseDataInner interface.
 */
export function instanceOfStatisticsReceiverResponseDataInner(value: object): value is StatisticsReceiverResponseDataInner {
    
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    
    
    if (!('receiver' in value) || value['receiver'] === undefined) return false;
    
    
    
    return true;
}

export function StatisticsReceiverResponseDataInnerFromJSON(json: any): StatisticsReceiverResponseDataInner {
    return StatisticsReceiverResponseDataInnerFromJSONTyped(json, false);
}

export function StatisticsReceiverResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticsReceiverResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'bytes': json['bytes'],
        
        'count': json['count'] == null ? undefined : json['count'],
        
        'receiver': json['receiver'],
        
        'spamcount': json['spamcount'] == null ? undefined : json['spamcount'],
        
        'viruscount': json['viruscount'] == null ? undefined : json['viruscount'],
        
    };
}

export function StatisticsReceiverResponseDataInnerToJSON(json: any): StatisticsReceiverResponseDataInner {
    return StatisticsReceiverResponseDataInnerToJSONTyped(json, false);
}

export function StatisticsReceiverResponseDataInnerToJSONTyped(value?: StatisticsReceiverResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'bytes': value['bytes'],
        
        'count': value['count'],
        
        'receiver': value['receiver'],
        
        'spamcount': value['spamcount'],
        
        'viruscount': value['viruscount'],
        
    };
}

