/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatisticsVirusResponseDataInner
 */
export interface StatisticsVirusResponseDataInner {

    /**
     * Detection count.
     * @type {number}
     * @memberof StatisticsVirusResponseDataInner
     */
    count: number;

    /**
     * Virus name.
     * @type {string}
     * @memberof StatisticsVirusResponseDataInner
     */
    name: string;

}

/**
 * Check if a given object implements the StatisticsVirusResponseDataInner interface.
 */
export function instanceOfStatisticsVirusResponseDataInner(value: object): value is StatisticsVirusResponseDataInner {
    
    if (!('count' in value) || value['count'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    return true;
}

export function StatisticsVirusResponseDataInnerFromJSON(json: any): StatisticsVirusResponseDataInner {
    return StatisticsVirusResponseDataInnerFromJSONTyped(json, false);
}

export function StatisticsVirusResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticsVirusResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'count': json['count'],
        
        'name': json['name'],
        
    };
}

export function StatisticsVirusResponseDataInnerToJSON(json: any): StatisticsVirusResponseDataInner {
    return StatisticsVirusResponseDataInnerToJSONTyped(json, false);
}

export function StatisticsVirusResponseDataInnerToJSONTyped(value?: StatisticsVirusResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'count': value['count'],
        
        'name': value['name'],
        
    };
}

