/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatisticsContactResponseDataInner
 */
export interface StatisticsContactResponseDataInner {

    /**
     * Mail traffic (Bytes).
     * @type {number}
     * @memberof StatisticsContactResponseDataInner
     */
    bytes: number;

    /**
     * Contact email.
     * @type {string}
     * @memberof StatisticsContactResponseDataInner
     */
    contact: string;

    /**
     * Mail count.
     * @type {number}
     * @memberof StatisticsContactResponseDataInner
     */
    count?: number;

    /**
     * Number of sent virus mails.
     * @type {number}
     * @memberof StatisticsContactResponseDataInner
     */
    viruscount?: number;

}

/**
 * Check if a given object implements the StatisticsContactResponseDataInner interface.
 */
export function instanceOfStatisticsContactResponseDataInner(value: object): value is StatisticsContactResponseDataInner {
    
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    
    if (!('contact' in value) || value['contact'] === undefined) return false;
    
    
    
    return true;
}

export function StatisticsContactResponseDataInnerFromJSON(json: any): StatisticsContactResponseDataInner {
    return StatisticsContactResponseDataInnerFromJSONTyped(json, false);
}

export function StatisticsContactResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticsContactResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'bytes': json['bytes'],
        
        'contact': json['contact'],
        
        'count': json['count'] == null ? undefined : json['count'],
        
        'viruscount': json['viruscount'] == null ? undefined : json['viruscount'],
        
    };
}

export function StatisticsContactResponseDataInnerToJSON(json: any): StatisticsContactResponseDataInner {
    return StatisticsContactResponseDataInnerToJSONTyped(json, false);
}

export function StatisticsContactResponseDataInnerToJSONTyped(value?: StatisticsContactResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'bytes': value['bytes'],
        
        'contact': value['contact'],
        
        'count': value['count'],
        
        'viruscount': value['viruscount'],
        
    };
}

