/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Mail Gateway API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatisticsRecentResponseDataInner } from './StatisticsRecentResponseDataInner';
import {
    StatisticsRecentResponseDataInnerFromJSON,
    StatisticsRecentResponseDataInnerFromJSONTyped,
    StatisticsRecentResponseDataInnerToJSON,
    StatisticsRecentResponseDataInnerToJSONTyped,
} from './StatisticsRecentResponseDataInner';

/**
 * 
 * @export
 * @interface StatisticsRecentResponse
 */
export interface StatisticsRecentResponse {

    /**
     * 
     * @type {Array<StatisticsRecentResponseDataInner>}
     * @memberof StatisticsRecentResponse
     */
    data: Array<StatisticsRecentResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof StatisticsRecentResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof StatisticsRecentResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the StatisticsRecentResponse interface.
 */
export function instanceOfStatisticsRecentResponse(value: object): value is StatisticsRecentResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function StatisticsRecentResponseFromJSON(json: any): StatisticsRecentResponse {
    return StatisticsRecentResponseFromJSONTyped(json, false);
}

export function StatisticsRecentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticsRecentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(StatisticsRecentResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function StatisticsRecentResponseToJSON(json: any): StatisticsRecentResponse {
    return StatisticsRecentResponseToJSONTyped(json, false);
}

export function StatisticsRecentResponseToJSONTyped(value?: StatisticsRecentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(StatisticsRecentResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

