/* tslint:disable */
/* eslint-disable */
// Auto-generated by scripts/sdk-facades.ts. Do not edit.

import { Configuration } from './runtime';
import { AccessApi } from './apis/AccessApi';
import { AccessAuthRealmApi } from './apis/AccessAuthRealmApi';
import { AccessOidcApi } from './apis/AccessOidcApi';
import { AccessTfaApi } from './apis/AccessTfaApi';
import { AccessTicketApi } from './apis/AccessTicketApi';
import { AccessUsersApi } from './apis/AccessUsersApi';
import { ConfigApi } from './apis/ConfigApi';
import { ConfigAcmeApi } from './apis/ConfigAcmeApi';
import { ConfigAdminApi } from './apis/ConfigAdminApi';
import { ConfigClamavApi } from './apis/ConfigClamavApi';
import { ConfigClusterApi } from './apis/ConfigClusterApi';
import { ConfigCustomscoresApi } from './apis/ConfigCustomscoresApi';
import { ConfigDkimApi } from './apis/ConfigDkimApi';
import { ConfigDomainsApi } from './apis/ConfigDomainsApi';
import { ConfigFetchmailApi } from './apis/ConfigFetchmailApi';
import { ConfigLdapApi } from './apis/ConfigLdapApi';
import { ConfigMailApi } from './apis/ConfigMailApi';
import { ConfigMynetworksApi } from './apis/ConfigMynetworksApi';
import { ConfigPbsApi } from './apis/ConfigPbsApi';
import { ConfigRuledbApi } from './apis/ConfigRuledbApi';
import { ConfigSpamApi } from './apis/ConfigSpamApi';
import { ConfigSpamquarApi } from './apis/ConfigSpamquarApi';
import { ConfigTfaApi } from './apis/ConfigTfaApi';
import { ConfigTlsInboundDomainsApi } from './apis/ConfigTlsInboundDomainsApi';
import { ConfigTlspolicyApi } from './apis/ConfigTlspolicyApi';
import { ConfigTransportApi } from './apis/ConfigTransportApi';
import { ConfigVirusquarApi } from './apis/ConfigVirusquarApi';
import { ConfigWelcomelistApi } from './apis/ConfigWelcomelistApi';
import { ConfigWhitelistApi } from './apis/ConfigWhitelistApi';
import { NodesApi } from './apis/NodesApi';
import { NodesAptApi } from './apis/NodesAptApi';
import { NodesBackupApi } from './apis/NodesBackupApi';
import { NodesCertificatesApi } from './apis/NodesCertificatesApi';
import { NodesClamavApi } from './apis/NodesClamavApi';
import { NodesConfigApi } from './apis/NodesConfigApi';
import { NodesDnsApi } from './apis/NodesDnsApi';
import { NodesNetworkApi } from './apis/NodesNetworkApi';
import { NodesPbsApi } from './apis/NodesPbsApi';
import { NodesPostfixApi } from './apis/NodesPostfixApi';
import { NodesServicesApi } from './apis/NodesServicesApi';
import { NodesSpamassassinApi } from './apis/NodesSpamassassinApi';
import { NodesStatusApi } from './apis/NodesStatusApi';
import { NodesSubscriptionApi } from './apis/NodesSubscriptionApi';
import { NodesTasksApi } from './apis/NodesTasksApi';
import { NodesTimeApi } from './apis/NodesTimeApi';
import { NodesTrackerApi } from './apis/NodesTrackerApi';
import { QuarantineApi } from './apis/QuarantineApi';
import { QuarantineBlacklistApi } from './apis/QuarantineBlacklistApi';
import { QuarantineBlocklistApi } from './apis/QuarantineBlocklistApi';
import { QuarantineContentApi } from './apis/QuarantineContentApi';
import { QuarantineWelcomelistApi } from './apis/QuarantineWelcomelistApi';
import { QuarantineWhitelistApi } from './apis/QuarantineWhitelistApi';
import { StatisticsApi } from './apis/StatisticsApi';
import { VersionApi } from './apis/VersionApi';

export class Client {
    // Renamed from `config` to dodge collisions with per-tag method names —
    // PBS/PMG/PDM all expose a `Config` tag, which would emit a `config()`
    // method on this class. Using `_configuration` keeps the property
    // distinct from any tag-derived accessor.
    protected _configuration: Configuration;

    protected _access?: AccessApi;
    protected _accessAuthRealm?: AccessAuthRealmApi;
    protected _accessOidc?: AccessOidcApi;
    protected _accessTfa?: AccessTfaApi;
    protected _accessTicket?: AccessTicketApi;
    protected _accessUsers?: AccessUsersApi;
    protected _config?: ConfigApi;
    protected _configAcme?: ConfigAcmeApi;
    protected _configAdmin?: ConfigAdminApi;
    protected _configClamav?: ConfigClamavApi;
    protected _configCluster?: ConfigClusterApi;
    protected _configCustomscores?: ConfigCustomscoresApi;
    protected _configDkim?: ConfigDkimApi;
    protected _configDomains?: ConfigDomainsApi;
    protected _configFetchmail?: ConfigFetchmailApi;
    protected _configLdap?: ConfigLdapApi;
    protected _configMail?: ConfigMailApi;
    protected _configMynetworks?: ConfigMynetworksApi;
    protected _configPbs?: ConfigPbsApi;
    protected _configRuledb?: ConfigRuledbApi;
    protected _configSpam?: ConfigSpamApi;
    protected _configSpamquar?: ConfigSpamquarApi;
    protected _configTfa?: ConfigTfaApi;
    protected _configTlsInboundDomains?: ConfigTlsInboundDomainsApi;
    protected _configTlspolicy?: ConfigTlspolicyApi;
    protected _configTransport?: ConfigTransportApi;
    protected _configVirusquar?: ConfigVirusquarApi;
    protected _configWelcomelist?: ConfigWelcomelistApi;
    protected _configWhitelist?: ConfigWhitelistApi;
    protected _nodes?: NodesApi;
    protected _nodesApt?: NodesAptApi;
    protected _nodesBackup?: NodesBackupApi;
    protected _nodesCertificates?: NodesCertificatesApi;
    protected _nodesClamav?: NodesClamavApi;
    protected _nodesConfig?: NodesConfigApi;
    protected _nodesDns?: NodesDnsApi;
    protected _nodesNetwork?: NodesNetworkApi;
    protected _nodesPbs?: NodesPbsApi;
    protected _nodesPostfix?: NodesPostfixApi;
    protected _nodesServices?: NodesServicesApi;
    protected _nodesSpamassassin?: NodesSpamassassinApi;
    protected _nodesStatus?: NodesStatusApi;
    protected _nodesSubscription?: NodesSubscriptionApi;
    protected _nodesTasks?: NodesTasksApi;
    protected _nodesTime?: NodesTimeApi;
    protected _nodesTracker?: NodesTrackerApi;
    protected _quarantine?: QuarantineApi;
    protected _quarantineBlacklist?: QuarantineBlacklistApi;
    protected _quarantineBlocklist?: QuarantineBlocklistApi;
    protected _quarantineContent?: QuarantineContentApi;
    protected _quarantineWelcomelist?: QuarantineWelcomelistApi;
    protected _quarantineWhitelist?: QuarantineWhitelistApi;
    protected _statistics?: StatisticsApi;
    protected _version?: VersionApi;

    constructor(config: Configuration) {
        this._configuration = config;
    }

    configuration(): Configuration {
        return this._configuration;
    }

    access(): AccessApi {
        return this._access ??= new AccessApi(this._configuration);
    }

    accessAuthRealm(): AccessAuthRealmApi {
        return this._accessAuthRealm ??= new AccessAuthRealmApi(this._configuration);
    }

    accessOidc(): AccessOidcApi {
        return this._accessOidc ??= new AccessOidcApi(this._configuration);
    }

    accessTfa(): AccessTfaApi {
        return this._accessTfa ??= new AccessTfaApi(this._configuration);
    }

    accessTicket(): AccessTicketApi {
        return this._accessTicket ??= new AccessTicketApi(this._configuration);
    }

    accessUsers(): AccessUsersApi {
        return this._accessUsers ??= new AccessUsersApi(this._configuration);
    }

    config(): ConfigApi {
        return this._config ??= new ConfigApi(this._configuration);
    }

    configAcme(): ConfigAcmeApi {
        return this._configAcme ??= new ConfigAcmeApi(this._configuration);
    }

    configAdmin(): ConfigAdminApi {
        return this._configAdmin ??= new ConfigAdminApi(this._configuration);
    }

    configClamav(): ConfigClamavApi {
        return this._configClamav ??= new ConfigClamavApi(this._configuration);
    }

    configCluster(): ConfigClusterApi {
        return this._configCluster ??= new ConfigClusterApi(this._configuration);
    }

    configCustomscores(): ConfigCustomscoresApi {
        return this._configCustomscores ??= new ConfigCustomscoresApi(this._configuration);
    }

    configDkim(): ConfigDkimApi {
        return this._configDkim ??= new ConfigDkimApi(this._configuration);
    }

    configDomains(): ConfigDomainsApi {
        return this._configDomains ??= new ConfigDomainsApi(this._configuration);
    }

    configFetchmail(): ConfigFetchmailApi {
        return this._configFetchmail ??= new ConfigFetchmailApi(this._configuration);
    }

    configLdap(): ConfigLdapApi {
        return this._configLdap ??= new ConfigLdapApi(this._configuration);
    }

    configMail(): ConfigMailApi {
        return this._configMail ??= new ConfigMailApi(this._configuration);
    }

    configMynetworks(): ConfigMynetworksApi {
        return this._configMynetworks ??= new ConfigMynetworksApi(this._configuration);
    }

    configPbs(): ConfigPbsApi {
        return this._configPbs ??= new ConfigPbsApi(this._configuration);
    }

    configRuledb(): ConfigRuledbApi {
        return this._configRuledb ??= new ConfigRuledbApi(this._configuration);
    }

    configSpam(): ConfigSpamApi {
        return this._configSpam ??= new ConfigSpamApi(this._configuration);
    }

    configSpamquar(): ConfigSpamquarApi {
        return this._configSpamquar ??= new ConfigSpamquarApi(this._configuration);
    }

    configTfa(): ConfigTfaApi {
        return this._configTfa ??= new ConfigTfaApi(this._configuration);
    }

    configTlsInboundDomains(): ConfigTlsInboundDomainsApi {
        return this._configTlsInboundDomains ??= new ConfigTlsInboundDomainsApi(this._configuration);
    }

    configTlspolicy(): ConfigTlspolicyApi {
        return this._configTlspolicy ??= new ConfigTlspolicyApi(this._configuration);
    }

    configTransport(): ConfigTransportApi {
        return this._configTransport ??= new ConfigTransportApi(this._configuration);
    }

    configVirusquar(): ConfigVirusquarApi {
        return this._configVirusquar ??= new ConfigVirusquarApi(this._configuration);
    }

    configWelcomelist(): ConfigWelcomelistApi {
        return this._configWelcomelist ??= new ConfigWelcomelistApi(this._configuration);
    }

    configWhitelist(): ConfigWhitelistApi {
        return this._configWhitelist ??= new ConfigWhitelistApi(this._configuration);
    }

    nodes(): NodesApi {
        return this._nodes ??= new NodesApi(this._configuration);
    }

    nodesApt(): NodesAptApi {
        return this._nodesApt ??= new NodesAptApi(this._configuration);
    }

    nodesBackup(): NodesBackupApi {
        return this._nodesBackup ??= new NodesBackupApi(this._configuration);
    }

    nodesCertificates(): NodesCertificatesApi {
        return this._nodesCertificates ??= new NodesCertificatesApi(this._configuration);
    }

    nodesClamav(): NodesClamavApi {
        return this._nodesClamav ??= new NodesClamavApi(this._configuration);
    }

    nodesConfig(): NodesConfigApi {
        return this._nodesConfig ??= new NodesConfigApi(this._configuration);
    }

    nodesDns(): NodesDnsApi {
        return this._nodesDns ??= new NodesDnsApi(this._configuration);
    }

    nodesNetwork(): NodesNetworkApi {
        return this._nodesNetwork ??= new NodesNetworkApi(this._configuration);
    }

    nodesPbs(): NodesPbsApi {
        return this._nodesPbs ??= new NodesPbsApi(this._configuration);
    }

    nodesPostfix(): NodesPostfixApi {
        return this._nodesPostfix ??= new NodesPostfixApi(this._configuration);
    }

    nodesServices(): NodesServicesApi {
        return this._nodesServices ??= new NodesServicesApi(this._configuration);
    }

    nodesSpamassassin(): NodesSpamassassinApi {
        return this._nodesSpamassassin ??= new NodesSpamassassinApi(this._configuration);
    }

    nodesStatus(): NodesStatusApi {
        return this._nodesStatus ??= new NodesStatusApi(this._configuration);
    }

    nodesSubscription(): NodesSubscriptionApi {
        return this._nodesSubscription ??= new NodesSubscriptionApi(this._configuration);
    }

    nodesTasks(): NodesTasksApi {
        return this._nodesTasks ??= new NodesTasksApi(this._configuration);
    }

    nodesTime(): NodesTimeApi {
        return this._nodesTime ??= new NodesTimeApi(this._configuration);
    }

    nodesTracker(): NodesTrackerApi {
        return this._nodesTracker ??= new NodesTrackerApi(this._configuration);
    }

    quarantine(): QuarantineApi {
        return this._quarantine ??= new QuarantineApi(this._configuration);
    }

    quarantineBlacklist(): QuarantineBlacklistApi {
        return this._quarantineBlacklist ??= new QuarantineBlacklistApi(this._configuration);
    }

    quarantineBlocklist(): QuarantineBlocklistApi {
        return this._quarantineBlocklist ??= new QuarantineBlocklistApi(this._configuration);
    }

    quarantineContent(): QuarantineContentApi {
        return this._quarantineContent ??= new QuarantineContentApi(this._configuration);
    }

    quarantineWelcomelist(): QuarantineWelcomelistApi {
        return this._quarantineWelcomelist ??= new QuarantineWelcomelistApi(this._configuration);
    }

    quarantineWhitelist(): QuarantineWhitelistApi {
        return this._quarantineWhitelist ??= new QuarantineWhitelistApi(this._configuration);
    }

    statistics(): StatisticsApi {
        return this._statistics ??= new StatisticsApi(this._configuration);
    }

    version(): VersionApi {
        return this._version ??= new VersionApi(this._configuration);
    }

}
